//! Shared golden-corpus harness for every `tests/golden_*.rs` test
//! (lane A's own `golden_smoke.rs`, and lane B/C/D's
//! `golden_{load,compile,compose}.rs`): rebuilding a case generated by
//! `electricity/scripts/_compiler_corpus.py` in a fresh temporary
//! directory ([`corpus`]) and the shared JSON shape that corpus
//! produces ([`reference`]).

pub mod corpus;
pub mod projection;
pub mod reference;
