//! Replays the golden corpus generated by
//! `electricity/scripts/generate_cel_corpus.py` against
//! [`electricity_cel::evaluate_condition`]/[`electricity_cel::evaluate_expect`].
//!
//! The corpus is checked in (`tests/golden/corpus.json`); CI separately
//! regenerates it with Python 3.11 and fails the build if it differs
//! (`.github/workflows/electricity.yml`), so this test only needs to
//! trust the committed file.

use chrono::{FixedOffset, NaiveDate, NaiveDateTime};
use electricity_cel::{evaluate_condition, evaluate_expect};
use electricity_value::{Dict, IntValue, Value};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(tag = "t")]
enum TaggedValue {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "bool")]
    Bool { v: bool },
    #[serde(rename = "int")]
    Int { v: String },
    #[serde(rename = "float")]
    Float { bits: String },
    #[serde(rename = "str")]
    Str { v: String },
    #[serde(rename = "bytes")]
    Bytes { v: String },
    #[serde(rename = "list")]
    List { v: Vec<TaggedValue> },
    #[serde(rename = "dict")]
    Dict { v: Vec<(TaggedValue, TaggedValue)> },
    #[serde(rename = "date")]
    Date { v: String },
    #[serde(rename = "datetime")]
    DateTime {
        naive: String,
        offset_seconds: Option<i64>,
    },
}

fn decode_hex(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

impl From<TaggedValue> for Value {
    fn from(tagged: TaggedValue) -> Self {
        match tagged {
            TaggedValue::None => Value::None,
            TaggedValue::Bool { v } => Value::Bool(v),
            TaggedValue::Int { v } => {
                Value::Int(IntValue::parse_decimal(&v).expect("valid decimal integer literal"))
            }
            TaggedValue::Float { bits } => {
                let bits = u64::from_str_radix(&bits, 16).expect("valid hex bit pattern");
                Value::Float(f64::from_bits(bits))
            }
            TaggedValue::Str { v } => Value::Str(v),
            TaggedValue::Bytes { v } => Value::Bytes(decode_hex(&v)),
            TaggedValue::List { v } => Value::List(v.into_iter().map(Value::from).collect()),
            TaggedValue::Dict { v } => {
                let mut dict = Dict::new();
                for (k, val) in v {
                    dict.insert(Value::from(k), Value::from(val));
                }
                Value::Dict(dict)
            }
            TaggedValue::Date { v } => {
                Value::Date(NaiveDate::parse_from_str(&v, "%Y-%m-%d").expect("valid ISO date"))
            }
            TaggedValue::DateTime {
                naive,
                offset_seconds,
            } => {
                let naive = NaiveDateTime::parse_from_str(&naive, "%Y-%m-%dT%H:%M:%S%.f")
                    .expect("valid ISO naive datetime");
                let offset = offset_seconds
                    .map(|secs| FixedOffset::east_opt(secs as i32).expect("valid UTC offset"));
                Value::DateTime(naive, offset)
            }
        }
    }
}

#[derive(Deserialize)]
#[serde(rename_all = "snake_case")]
enum Mode {
    Condition,
    Expect,
}

#[derive(Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum Outcome {
    Ok { result: bool },
    Error { message: Option<String> },
}

#[derive(Deserialize)]
struct Case {
    mode: Mode,
    expr: String,
    #[serde(default)]
    strict: bool,
    state: TaggedValue,
    #[serde(default)]
    value: Option<TaggedValue>,
    #[serde(default)]
    meta: Option<TaggedValue>,
    outcome: Outcome,
}

#[test]
fn golden_corpus_matches_circuitrys_real_cel_evaluator() {
    let text = include_str!("golden/corpus.json");
    let cases: Vec<Case> = serde_json::from_str(text).expect("golden/corpus.json is valid JSON");
    assert!(!cases.is_empty(), "golden corpus must not be empty");

    let mut failures = Vec::new();
    for (i, case) in cases.into_iter().enumerate() {
        let state = Value::from(case.state);
        let got = match case.mode {
            Mode::Condition => evaluate_condition(&case.expr, &state, case.strict),
            Mode::Expect => {
                let value = Value::from(case.value.expect("expect case needs `value`"));
                let meta = Value::from(case.meta.expect("expect case needs `meta`"));
                evaluate_expect(&case.expr, &value, &meta, &state)
            }
        };

        match (case.outcome, got) {
            (Outcome::Ok { result: expected }, Ok(actual)) if expected == actual => {}
            (Outcome::Ok { result: expected }, Ok(actual)) => failures.push(format!(
                "case {i}: expected Ok({expected}), got Ok({actual}) for {:?}",
                case.expr
            )),
            (Outcome::Ok { result: expected }, Err(err)) => failures.push(format!(
                "case {i}: expected Ok({expected}) for {:?}, got Err({err})",
                case.expr
            )),
            (Outcome::Error { message: None }, Err(err)) => {
                // Text from `cel`/`lark` itself only has to fail at the
                // same place with a non-empty message, not match
                // word-for-word (DESIGN.md §1, §12) — but it still has
                // to have *a* message, not a silently empty one, and it
                // must still carry Circuitry's own, exact prefix: every
                // non-Circuitry-worded failure is wrapped as
                // `CEL evaluation failed for {expr!r}: {cause}` by both
                // entry points (`lib.rs`), never left bare.
                let actual_message = err.to_string();
                let expected_prefix = format!(
                    "CEL evaluation failed for {}: ",
                    electricity_value::Value::Str(case.expr.clone()).py_repr()
                );
                if actual_message.is_empty() {
                    failures.push(format!(
                        "case {i}: error for {:?} has an empty message",
                        case.expr
                    ));
                } else if !actual_message.starts_with(&expected_prefix) {
                    failures.push(format!(
                        "case {i}: error for {:?} is missing Circuitry's own prefix\n  expected prefix: {expected_prefix:?}\n  got:             {actual_message:?}",
                        case.expr
                    ));
                }
            }
            (
                Outcome::Error {
                    message: Some(expected_message),
                },
                Err(err),
            ) => {
                let actual_message = err.to_string();
                if actual_message != expected_message {
                    failures.push(format!(
                        "case {i}: message mismatch for {:?}\n  expected: {expected_message:?}\n  got:      {actual_message:?}",
                        case.expr
                    ));
                }
            }
            (Outcome::Error { .. }, Ok(actual)) => failures.push(format!(
                "case {i}: expected an error for {:?}, got Ok({actual})",
                case.expr
            )),
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
