"""Deterministic complexity scoring for prompt effects.

A prompt's *complexity* here is a mechanical estimate of how much work the model
is being asked to do — not a judgement about the task, and never a model call.
Everything in this module is a pure function of its arguments: no adapter, no
store, no config read, no clock, no randomness, no IO. The same inputs always
produce the same number, which is what makes the score usable as a routing
input (pick a bigger model for a harder prompt) and as a lint signal.

Signals
-------

Seven signals are measured, each producing a raw measurement and a *normalized*
value in ``[0, 1]``:

===================  =======================================================
``prompt_size``      Token estimate of the prompt — the rendered prompt when
                     one is supplied, the template/messages otherwise.
``state_references`` Distinct ``{{...}}`` references in the template. More
                     interpolated state means more context to reconcile.
``output_type``      ``prompt_type``: ``boolean`` is cheap, ``array``/``json``
                     demand structure.
``schema_shape``     Depth and breadth of a declared output schema.
``output_size``      Declared output limits (``maxItems``, ``maxLength``,
                     ``max_tokens``) — how much text has to come back.
``structure``        Structural position: nesting depth, loop body, whether
                     the effect was generated by a reflector.
``keywords``         Deterministic keyword matching against a weight table.
                     String matching, not a model judgement.
===================  =======================================================

Scoring
-------

Each normalized value is multiplied by its weight, and the weighted mean is
scaled onto a bounded, documented range — ``0.0`` to :data:`MAX_SCORE` (100.0).
Because the score is a weighted *mean* it is portable: changing the weights
rescales the emphasis, not the range, so band tables written against 0–100 stay
valid.

    score = MAX_SCORE * Σ(weightᵢ × normalizedᵢ) / Σ(weightᵢ)

Every term of that sum is reported. :class:`SignalScore` carries the raw
measurement, the weight applied, the normalized value, and the contribution *in
score points*, so a total can be reconstructed by summing contributions — no
re-running the scorer to find out where a surprising number came from::

    result = score(effect)
    assert abs(sum(s.contribution for s in result.signals) - result.score) < 1e-6
    print(result.explain())

Modes
-----

Scoring works with or without a rendered prompt. With one (``mode="rendered"``)
the size signal measures what is actually being sent. Without one
(``mode="static"``, the default) it measures the template and the result is
flagged ``estimated=True`` — the interpolated state is not there yet, so the
real prompt is at least as large. Static mode is what ``cof score`` and lint
use; rendered mode is what the runtime uses once a prompt is materialized.

Degradation
-----------

Nothing here raises on bad input. Unknown ``prompt_type``, a schema that is not
a mapping, a weight that is not a number, a definition that is ``None`` — each
degrades to a neutral measurement and appends a line to
:attr:`ComplexityScore.warnings`.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Iterable, Literal, Mapping, Sequence

__all__ = [
    "DEFAULT_KEYWORD_WEIGHTS",
    "DEFAULT_WEIGHTS",
    "MAX_SCORE",
    "MIN_SCORE",
    "SIGNAL_NAMES",
    "ComplexityScore",
    "ScoreMode",
    "SignalScore",
    "StructureContext",
    "score",
]

#: Lowest possible score. A prompt cannot be less complex than nothing.
MIN_SCORE = 0.0

#: Highest possible score. Every signal saturated at its normalized maximum.
#: The range is fixed regardless of the weights supplied, so band tables
#: written against 0–100 stay portable across weight tunings.
MAX_SCORE = 100.0

#: Signals in report order. A weights mapping may name any subset; signals it
#: omits fall back to :data:`DEFAULT_WEIGHTS`.
SIGNAL_NAMES: tuple[str, ...] = (
    "prompt_size",
    "state_references",
    "output_type",
    "schema_shape",
    "output_size",
    "structure",
    "keywords",
)

#: Default signal weights. They sum to 1.0 for readability only — the score
#: divides by the weight total, so any positive scale behaves identically.
#:
#: The relative ordering these produce is the contract: a one-line rewrite
#: scores below a multi-reference synthesis, which scores below a
#: schema-constrained extraction over a large interpolated blob. Size carries
#: the most weight because it is the signal that correlates most directly with
#: model effort; keywords carry the least because string matching is the
#: weakest evidence of the three kinds here (measured, declared, guessed).
DEFAULT_WEIGHTS: Mapping[str, float] = {
    "prompt_size": 0.28,
    "state_references": 0.18,
    "output_type": 0.14,
    "schema_shape": 0.16,
    "output_size": 0.10,
    "structure": 0.08,
    "keywords": 0.06,
}

#: Default keyword table: lowercase phrase -> weight added to the ``keywords``
#: signal when the phrase appears (whole-word match, case-insensitive). The sum
#: of matched weights is clamped to 1.0. Pass ``keyword_weights={}`` to disable
#: the signal entirely, or a table of your own to replace this one.
#:
#: Phrases are graded by how much reasoning the verb implies: transformation of
#: given text is cheap, multi-source synthesis and proof are not.
DEFAULT_KEYWORD_WEIGHTS: Mapping[str, float] = {
    "analyze": 0.15,
    "chain of thought": 0.25,
    "classify": 0.10,
    "compare": 0.15,
    "critique": 0.20,
    "cross-reference": 0.25,
    "deduce": 0.25,
    "derive": 0.20,
    "evaluate": 0.15,
    "explain why": 0.20,
    "extract": 0.15,
    "infer": 0.20,
    "justify": 0.20,
    "plan": 0.20,
    "prove": 0.30,
    "reason": 0.20,
    "reconcile": 0.25,
    "rewrite": 0.05,
    "step by step": 0.25,
    "summarize": 0.10,
    "synthesize": 0.25,
    "translate": 0.10,
    "weigh": 0.15,
}

#: Normalized value per ``prompt_type``. Unknown types fall back to ``text``
#: and add a warning.
_TYPE_NORMALS: Mapping[str, float] = {
    "boolean": 0.05,
    "number": 0.10,
    "text": 0.25,
    "tool": 0.40,
    "json": 0.60,
    "object": 0.60,
    "array": 0.75,
}

#: Characters per token. Crude on purpose: the scorer must not depend on a
#: tokenizer library, and a constant divisor keeps the estimate deterministic
#: across models. Contributions are relative, so a systematic bias cancels.
_CHARS_PER_TOKEN = 4

#: Half-points for the saturating curve ``v / (v + k)``: the measurement at
#: which a signal reaches 0.5. The curve is monotone and bounded, so no
#: measurement — however extreme — can push a signal past 1.0.
_SIZE_HALF_TOKENS = 800.0
_REFERENCE_HALF_COUNT = 4.0
_SCHEMA_DEPTH_HALF = 3.0
_SCHEMA_FIELDS_HALF = 10.0
_OUTPUT_SIZE_HALF_TOKENS = 512.0
_DEPTH_HALF = 3.0

#: Tokens assumed per declared output item when a schema caps ``maxItems`` but
#: declares no per-item length.
_TOKENS_PER_ITEM = 32

#: Mustache tags that are not state references: comments, partials, closing
#: tags, and the ``.`` implicit iterator.
_TAG_RE = re.compile(r"\{\{\{?\s*([#^/&!>]?)\s*([^{}]*?)\s*\}?\}\}")

#: Rounding applied to every reported float. Six places is far below any
#: meaningful weight difference and keeps repr stable across platforms.
_PLACES = 6

ScoreMode = Literal["static", "rendered"]


def _round(value: float) -> float:
    return round(float(value), _PLACES)


def _number(value: Any) -> float:
    """Best-effort float. Weights arrive pre-validated; this is the backstop."""
    coerced = _as_number(value)
    return 0.0 if coerced is None else coerced


def _clamp01(value: float) -> float:
    return 0.0 if value < 0.0 else (1.0 if value > 1.0 else value)


def _saturate(value: float, half: float) -> float:
    """``value / (value + half)`` — 0 at 0, 0.5 at ``half``, never reaching 1."""
    if value <= 0 or half <= 0:
        return 0.0
    return float(value) / (float(value) + half)


def _as_number(value: Any) -> float | None:
    """Coerce to float, or ``None`` when the value is not a plain number.

    ``bool`` is excluded deliberately: ``True`` is not a size of 1.
    """
    if isinstance(value, bool) or value is None:
        return None
    if isinstance(value, (int, float)):
        return float(value)
    return None


def _estimate_tokens(text: str) -> int:
    """Token estimate for a blob of text. Ceiling division by 4 characters."""
    if not text:
        return 0
    return (len(text) + _CHARS_PER_TOKEN - 1) // _CHARS_PER_TOKEN


@dataclass(frozen=True)
class StructureContext:
    """Where an effect sits in the orchestration.

    Supplied by the caller (the runtime knows its own nesting); the scorer
    never walks a tree itself. Every field defaults to the top-level case, so
    an omitted context is equivalent to "a plain effect at the root".
    """

    #: Nesting depth. 0 = top-level effect in the orchestration.
    depth: int = 0

    #: How many loop bodies enclose the effect. >= 1 means it runs repeatedly
    #: over inputs that vary per iteration.
    loop_depth: int = 0

    #: The effect was emitted by a reflector rather than authored by hand.
    reflector_generated: bool = False

    @property
    def in_loop(self) -> bool:
        return self.loop_depth > 0

    @classmethod
    def from_any(cls, value: Any) -> tuple["StructureContext", list[str]]:
        """Build a context from a mapping, an instance, or ``None``.

        Returns the context plus any warnings raised while coercing it. Junk
        values degrade to the default rather than raising.
        """
        if value is None:
            return cls(), []
        if isinstance(value, StructureContext):
            return value, []

        warnings: list[str] = []
        if isinstance(value, Mapping):
            get = value.get
        elif hasattr(value, "depth") or hasattr(value, "loop_depth"):

            def get(key: str, default: Any = None) -> Any:
                return getattr(value, key, default)

        else:
            return cls(), [
                f"structure: expected a mapping or StructureContext, got "
                f"{type(value).__name__}; treated as top-level."
            ]

        def _int(key: str) -> int:
            raw = get(key, 0)
            number = _as_number(raw)
            if number is None:
                if raw not in (None, 0):
                    warnings.append(
                        f"structure.{key}: {raw!r} is not a number; treated as 0."
                    )
                return 0
            if number < 0:
                warnings.append(f"structure.{key}: {raw!r} is negative; treated as 0.")
                return 0
            return int(number)

        # ``in_loop`` is accepted as a convenience spelling of loop_depth >= 1.
        loop_depth = _int("loop_depth")
        if loop_depth == 0 and bool(get("in_loop", False)):
            loop_depth = 1

        return (
            cls(
                depth=_int("depth"),
                loop_depth=loop_depth,
                reflector_generated=bool(get("reflector_generated", False)),
            ),
            warnings,
        )


@dataclass(frozen=True)
class SignalScore:
    """One signal's measurement and its share of the total.

    ``contribution`` is already in score points, so summing the contributions
    of every signal reproduces :attr:`ComplexityScore.score` exactly (to within
    float rounding). That is the whole point: a surprising score can be argued
    with by reading the breakdown, without re-running the scorer.
    """

    #: Signal name, one of :data:`SIGNAL_NAMES`.
    name: str

    #: The raw mechanical measurement — a token count, a reference count, a
    #: schema field count. Always a number so breakdowns stay comparable.
    raw: float

    #: ``raw`` mapped onto ``[0, 1]``.
    normalized: float

    #: Weight applied, after fallback/clamping.
    weight: float

    #: ``MAX_SCORE * weight * normalized / weight_total`` — score points.
    contribution: float

    #: True when the measurement is inferred rather than observed (e.g. a
    #: template's size standing in for the rendered prompt's).
    estimated: bool = False

    #: Signal-specific supporting detail: the reference names that were
    #: counted, the schema depth behind a field count, and so on.
    detail: Mapping[str, Any] = field(default_factory=dict)

    #: One-line human-readable explanation of the measurement.
    note: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "name": self.name,
            "raw": self.raw,
            "normalized": self.normalized,
            "weight": self.weight,
            "contribution": self.contribution,
            "estimated": self.estimated,
            "detail": dict(self.detail),
            "note": self.note,
        }


@dataclass(frozen=True)
class ComplexityScore:
    """A score plus the full breakdown that produced it."""

    #: The total, between :data:`MIN_SCORE` and :data:`MAX_SCORE`.
    score: float

    #: ``"rendered"`` when a materialized prompt was scored, ``"static"`` when
    #: only the template was available.
    mode: ScoreMode

    #: True when at least one signal is an inference rather than an
    #: observation — always true in static mode.
    estimated: bool

    #: Per-signal breakdown, in :data:`SIGNAL_NAMES` order.
    signals: tuple[SignalScore, ...]

    #: Sum of the applied weights — the divisor in the weighted mean.
    weight_total: float

    #: Non-fatal problems found while scoring: unknown prompt types, junk
    #: weights, missing templates. Never empty-on-error; scoring never raises.
    warnings: tuple[str, ...] = ()

    #: Upper bound of the range, restated so a serialized result is
    #: self-describing.
    max_score: float = MAX_SCORE

    def signal(self, name: str) -> SignalScore | None:
        """Look up one signal's breakdown by name."""
        for entry in self.signals:
            if entry.name == name:
                return entry
        return None

    def to_dict(self) -> dict[str, Any]:
        """JSON-serializable form of the whole result."""
        return {
            "score": self.score,
            "max_score": self.max_score,
            "mode": self.mode,
            "estimated": self.estimated,
            "weight_total": self.weight_total,
            "signals": [s.to_dict() for s in self.signals],
            "warnings": list(self.warnings),
        }

    def explain(self) -> str:
        """Render the breakdown as a plain-text table.

        Deterministic like everything else here — no colour, no width probing,
        no terminal access.
        """
        header = (
            f"complexity {self.score:.1f}/{self.max_score:.0f}"
            f"  ({self.mode}{', estimated' if self.estimated else ''})"
        )
        lines = [header, "-" * len(header)]
        name_width = max((len(s.name) for s in self.signals), default=0)
        for entry in self.signals:
            marker = "~" if entry.estimated else " "
            lines.append(
                f"{entry.name:<{name_width}} {marker}"
                f" raw={entry.raw:<10.4g}"
                f" norm={entry.normalized:.3f}"
                f" × w={entry.weight:.3f}"
                f" → {entry.contribution:6.2f}"
                f"   {entry.note}"
            )
        lines.append(
            f"{'total':<{name_width}}  "
            f"{' ' * 27}(Σw={self.weight_total:.3f})"
            f" → {self.score:6.2f}"
        )
        for warning in self.warnings:
            lines.append(f"! {warning}")
        return "\n".join(lines)


def _get(definition: Any, key: str, default: Any = None) -> Any:
    """Read ``key`` off a mapping or an object, whichever was handed in.

    Accepting both is deliberate: the runtime holds compiled
    ``PromptDefinition`` dataclasses while ``cof score`` and lint hold the raw
    YAML dicts, and this module imports neither (importing the compiled
    definitions would drag an adapter into a module that promises not to).
    """
    if definition is None:
        return default
    if isinstance(definition, Mapping):
        value = definition.get(key, default)
    else:
        value = getattr(definition, key, default)
    return default if value is None else value


def _message_text(messages: Any) -> str | None:
    """Join a messages sequence into one blob, or ``None`` if unusable."""
    if not isinstance(messages, Sequence) or isinstance(messages, (str, bytes)):
        return None
    parts: list[str] = []
    for message in messages:
        content = _get(message, "content", "")
        if isinstance(content, str) and content:
            parts.append(content)
    if not parts:
        return None
    return "\n\n".join(parts)


def _template_text(definition: Any, warnings: list[str]) -> str:
    """The authored prompt text: ``template``, else joined ``messages``."""
    template = _get(definition, "template")
    if isinstance(template, str) and template:
        return template
    if template is not None and not isinstance(template, str):
        warnings.append(
            f"template: expected a string, got {type(template).__name__}; ignored."
        )

    joined = _message_text(_get(definition, "messages"))
    if joined is not None:
        return joined
    return ""


def _extract_references(template: str) -> tuple[list[str], list[str]]:
    """Distinct mustache references in a template, plus its section names.

    Comments (``{{! ... }}``), partials (``{{> ... }}``) and closing tags are
    not references. Section openers (``{{#x}}`` / ``{{^x}}``) are: the section
    name is state being read, and the block is conditional on it.
    """
    references: list[str] = []
    sections: list[str] = []
    seen: set[str] = set()
    seen_sections: set[str] = set()

    for sigil, name in _TAG_RE.findall(template):
        if sigil in ("!", ">", "/"):
            continue
        cleaned = name.strip()
        if not cleaned or cleaned == ".":
            continue
        if sigil in ("#", "^") and cleaned not in seen_sections:
            seen_sections.add(cleaned)
            sections.append(cleaned)
        if cleaned not in seen:
            seen.add(cleaned)
            references.append(cleaned)

    return sorted(references), sorted(sections)


def _walk_schema(node: Any, depth: int = 1) -> tuple[int, int]:
    """Return ``(max_depth, field_count)`` for a JSON-Schema-ish mapping.

    Counts declared properties and array item shapes. Unknown keywords are
    skipped rather than guessed at; a schema that is not a mapping is depth 0.
    """
    if not isinstance(node, Mapping):
        return (0, 0)

    max_depth = depth
    fields = 0

    properties = node.get("properties")
    if isinstance(properties, Mapping):
        fields += len(properties)
        for child in properties.values():
            child_depth, child_fields = _walk_schema(child, depth + 1)
            max_depth = max(max_depth, child_depth)
            fields += child_fields

    items = node.get("items")
    if isinstance(items, Mapping):
        child_depth, child_fields = _walk_schema(items, depth + 1)
        max_depth = max(max_depth, child_depth)
        fields += child_fields
    elif isinstance(items, Sequence) and not isinstance(items, (str, bytes)):
        for child in items:
            child_depth, child_fields = _walk_schema(child, depth + 1)
            max_depth = max(max_depth, child_depth)
            fields += child_fields

    for keyword in ("oneOf", "anyOf", "allOf"):
        branches = node.get(keyword)
        if isinstance(branches, Sequence) and not isinstance(branches, (str, bytes)):
            for child in branches:
                child_depth, child_fields = _walk_schema(child, depth + 1)
                max_depth = max(max_depth, child_depth)
                fields += child_fields

    return (max_depth, fields)


def _declared_output_tokens(
    schema: Mapping[str, Any] | None, params: Any
) -> tuple[float, dict[str, Any]]:
    """Largest declared output size, expressed in estimated tokens.

    Reads ``max_tokens`` from params and ``maxLength`` / ``maxItems`` from the
    schema, converts each to a token estimate, and takes the largest. Nothing
    declared is a measurement of 0, not an error — most prompts declare no cap.
    """
    detail: dict[str, Any] = {}
    candidates: list[float] = []

    if isinstance(params, Mapping):
        for key in ("max_tokens", "num_predict", "max_output_tokens"):
            value = _as_number(params.get(key))
            if value is not None and value > 0:
                detail[key] = value
                candidates.append(value)

    if isinstance(schema, Mapping):
        max_length = _as_number(schema.get("maxLength"))
        if max_length is not None and max_length > 0:
            detail["maxLength"] = max_length
            candidates.append(max_length / _CHARS_PER_TOKEN)

        max_items = _as_number(schema.get("maxItems"))
        if max_items is not None and max_items > 0:
            detail["maxItems"] = max_items
            per_item = _as_number(
                (schema.get("items") or {}).get("maxLength")
                if isinstance(schema.get("items"), Mapping)
                else None
            )
            item_tokens = (
                per_item / _CHARS_PER_TOKEN
                if per_item is not None and per_item > 0
                else _TOKENS_PER_ITEM
            )
            candidates.append(max_items * item_tokens)

        max_properties = _as_number(schema.get("maxProperties"))
        if max_properties is not None and max_properties > 0:
            detail["maxProperties"] = max_properties
            candidates.append(max_properties * _TOKENS_PER_ITEM)

    return (max(candidates) if candidates else 0.0, detail)


#: Inflections a keyword is allowed to appear in. Matching is stem-based —
#: "analyze" also matches "analyzes", "analyzed", "analyzing" — but stops well
#: short of stemming properly, because a stemmer is a dependency and a source
#: of surprise. A phrase that must match exactly can be spelled with its own
#: suffix in the table.
_KEYWORD_SUFFIXES = r"(?:e|es|s|ed|ing|ion|ions)?"


def _keyword_pattern(phrase: str) -> str:
    stem = phrase.lower().strip()
    if len(stem) > 3 and stem.endswith("e"):
        stem = stem[:-1]
    return r"\b" + re.escape(stem) + _KEYWORD_SUFFIXES + r"\b"


def _match_keywords(
    haystack: str, table: Mapping[str, float]
) -> list[tuple[str, float]]:
    """Whole-word, case-insensitive phrase matches, sorted by phrase.

    Sorted so the breakdown is byte-identical run to run regardless of the
    table's iteration order.
    """
    if not haystack or not table:
        return []
    lowered = haystack.lower()
    matches: list[tuple[str, float]] = []
    for phrase, raw_weight in table.items():
        if not isinstance(phrase, str) or not phrase.strip():
            continue
        weight = _as_number(raw_weight)
        if weight is None or weight <= 0:
            continue
        if re.search(_keyword_pattern(phrase), lowered):
            matches.append((phrase, weight))
    return sorted(matches)


def _resolve_weights(
    weights: Mapping[str, float] | None, warnings: list[str]
) -> dict[str, float]:
    """Weights for every signal, filling gaps from :data:`DEFAULT_WEIGHTS`.

    A caller may pass a partial table, a table with junk in it, or nothing at
    all. Unknown keys are reported and ignored; negative weights are clamped to
    zero so the bounded range holds.
    """
    resolved = {name: float(DEFAULT_WEIGHTS[name]) for name in SIGNAL_NAMES}
    if weights is None:
        return resolved
    if not isinstance(weights, Mapping):
        warnings.append(
            f"weights: expected a mapping, got {type(weights).__name__}; "
            "used defaults."
        )
        return resolved

    for key in sorted(str(k) for k in weights.keys()):
        if key not in resolved:
            warnings.append(f"weights.{key}: unknown signal; ignored.")

    for name in SIGNAL_NAMES:
        if name not in weights:
            continue
        value = _as_number(weights[name])
        if value is None:
            warnings.append(
                f"weights.{name}: {weights[name]!r} is not a number; "
                f"used default {resolved[name]}."
            )
            continue
        if value < 0:
            warnings.append(f"weights.{name}: {value!r} is negative; clamped to 0.")
            value = 0.0
        resolved[name] = value

    return resolved


def _prompt_type(definition: Any, warnings: list[str]) -> tuple[str, float]:
    raw = _get(definition, "prompt_type", "text")
    if not isinstance(raw, str):
        warnings.append(
            f"prompt_type: expected a string, got {type(raw).__name__}; "
            "treated as 'text'."
        )
        return ("text", _TYPE_NORMALS["text"])
    cleaned = raw.strip().lower() or "text"
    if cleaned not in _TYPE_NORMALS:
        warnings.append(f"prompt_type: unknown type {raw!r}; treated as 'text'.")
        return (cleaned, _TYPE_NORMALS["text"])
    return (cleaned, _TYPE_NORMALS[cleaned])


def _schema_of(definition: Any, warnings: list[str]) -> Mapping[str, Any] | None:
    schema = _get(definition, "schema")
    if schema is None:
        return None
    if not isinstance(schema, Mapping):
        warnings.append(
            f"schema: expected a mapping, got {type(schema).__name__}; ignored."
        )
        return None
    return schema


def score(
    definition: Any = None,
    *,
    rendered_prompt: str | None = None,
    weights: Mapping[str, float] | None = None,
    keyword_weights: Mapping[str, float] | None = None,
    structure: StructureContext | Mapping[str, Any] | None = None,
) -> ComplexityScore:
    """Score a prompt effect's complexity, with the breakdown that produced it.

    Pure and deterministic: repeated calls on identical inputs return identical
    results, and nothing here reads config, touches a store, or calls a model.

    :param definition: A prompt definition — either a compiled definition
        object or the raw effect mapping from YAML. Read for ``template`` /
        ``messages``, ``prompt_type``, ``schema``, ``params`` and
        ``description``. ``None`` scores as an empty prompt with a warning.
    :param rendered_prompt: The materialized prompt, when one exists. Supplying
        it switches the result to ``mode="rendered"`` and measures real size
        instead of template size.
    :param weights: Per-signal weights, keyed by :data:`SIGNAL_NAMES`. Partial
        tables are filled from :data:`DEFAULT_WEIGHTS`. Taken as an argument on
        purpose — this module does not read ``runtime.complexity.scoring``, its
        caller does.
    :param keyword_weights: Keyword table for the ``keywords`` signal.
        Defaults to :data:`DEFAULT_KEYWORD_WEIGHTS`; pass ``{}`` to disable.
    :param structure: Where the effect sits — a :class:`StructureContext` or a
        mapping with ``depth`` / ``loop_depth`` / ``reflector_generated``.
    :returns: A :class:`ComplexityScore` between :data:`MIN_SCORE` and
        :data:`MAX_SCORE`.
    """
    warnings: list[str] = []

    if definition is None and rendered_prompt is None:
        warnings.append("definition: nothing to score; every signal read as empty.")
    elif definition is not None and not isinstance(definition, Mapping):
        # Objects are fine (duck-typed via getattr) but scalars are not.
        if isinstance(definition, (str, bytes, int, float, bool)):
            warnings.append(
                f"definition: expected a mapping or definition object, got "
                f"{type(definition).__name__}; every signal read as empty."
            )
            definition = None

    resolved_weights = _resolve_weights(weights, warnings)
    context, structure_warnings = StructureContext.from_any(structure)
    warnings.extend(structure_warnings)

    table = (
        DEFAULT_KEYWORD_WEIGHTS if keyword_weights is None else keyword_weights
    )
    if not isinstance(table, Mapping):
        warnings.append(
            f"keyword_weights: expected a mapping, got {type(table).__name__}; "
            "used defaults."
        )
        table = DEFAULT_KEYWORD_WEIGHTS

    template = _template_text(definition, warnings)
    mode: ScoreMode = "rendered" if isinstance(rendered_prompt, str) else "static"
    if rendered_prompt is not None and not isinstance(rendered_prompt, str):
        warnings.append(
            f"rendered_prompt: expected a string, got "
            f"{type(rendered_prompt).__name__}; scored in static mode."
        )
    if mode == "static" and definition is not None and not template:
        warnings.append(
            "template: no template or messages found; size read as empty."
        )

    measured: list[tuple[str, float, float, bool, dict[str, Any], str]] = []

    # --- prompt_size ---------------------------------------------------
    sized_text = rendered_prompt if mode == "rendered" else template
    tokens = _estimate_tokens(sized_text or "")
    size_estimated = mode == "static"
    measured.append(
        (
            "prompt_size",
            float(tokens),
            _saturate(tokens, _SIZE_HALF_TOKENS),
            size_estimated,
            {
                "characters": len(sized_text or ""),
                "tokens": tokens,
                "source": "rendered_prompt" if mode == "rendered" else "template",
                "chars_per_token": _CHARS_PER_TOKEN,
                "half_point_tokens": _SIZE_HALF_TOKENS,
            },
            (
                f"~{tokens} tokens of "
                f"{'rendered prompt' if mode == 'rendered' else 'template (estimate)'}"
            ),
        )
    )

    # --- state_references ----------------------------------------------
    # Always read off the template: a rendered prompt has already had its
    # references substituted away, so counting there would report zero.
    references, sections = _extract_references(template)
    measured.append(
        (
            "state_references",
            float(len(references)),
            _saturate(len(references), _REFERENCE_HALF_COUNT),
            False,
            {
                "references": references,
                "sections": sections,
                "half_point_count": _REFERENCE_HALF_COUNT,
            },
            f"{len(references)} distinct reference(s)"
            + (f", {len(sections)} section(s)" if sections else ""),
        )
    )

    # --- output_type -----------------------------------------------------
    type_name, type_normal = _prompt_type(definition, warnings)
    measured.append(
        (
            "output_type",
            type_normal,
            type_normal,
            False,
            {"prompt_type": type_name, "scale": dict(_TYPE_NORMALS)},
            f"prompt_type={type_name}",
        )
    )

    # --- schema_shape ----------------------------------------------------
    schema = _schema_of(definition, warnings)
    schema_depth, schema_fields = _walk_schema(schema)
    schema_normal = _clamp01(
        0.5 * _saturate(schema_depth, _SCHEMA_DEPTH_HALF)
        + 0.5 * _saturate(schema_fields, _SCHEMA_FIELDS_HALF)
    )
    measured.append(
        (
            "schema_shape",
            float(schema_fields),
            schema_normal,
            False,
            {
                "depth": schema_depth,
                "fields": schema_fields,
                "declared": schema is not None,
                "half_point_depth": _SCHEMA_DEPTH_HALF,
                "half_point_fields": _SCHEMA_FIELDS_HALF,
            },
            (
                f"schema depth {schema_depth}, {schema_fields} field(s)"
                if schema is not None
                else "no schema declared"
            ),
        )
    )

    # --- output_size -----------------------------------------------------
    output_tokens, output_detail = _declared_output_tokens(
        schema, _get(definition, "params")
    )
    measured.append(
        (
            "output_size",
            _round(output_tokens),
            _saturate(output_tokens, _OUTPUT_SIZE_HALF_TOKENS),
            # Declared limits are read, not guessed, so this is not an
            # estimate — ``estimated`` is reserved for the static-mode size
            # signal, which keeps ``ComplexityScore.estimated`` exactly
            # equivalent to ``mode == "static"``.
            False,
            {
                **output_detail,
                "estimated_tokens": _round(output_tokens),
                "tokens_per_item": _TOKENS_PER_ITEM,
                "half_point_tokens": _OUTPUT_SIZE_HALF_TOKENS,
            },
            (
                f"~{output_tokens:.0f} tokens declared "
                f"({', '.join(sorted(output_detail))})"
                if output_detail
                else "no declared output limit"
            ),
        )
    )

    # --- structure -------------------------------------------------------
    structure_normal = _clamp01(
        0.5 * _saturate(context.depth, _DEPTH_HALF)
        + 0.15 * min(context.loop_depth, 2)
        + (0.2 if context.reflector_generated else 0.0)
    )
    structure_notes = [f"depth {context.depth}"]
    if context.in_loop:
        structure_notes.append(f"inside {context.loop_depth} loop(s)")
    if context.reflector_generated:
        structure_notes.append("reflector-generated")
    measured.append(
        (
            "structure",
            float(context.depth),
            structure_normal,
            False,
            {
                "depth": context.depth,
                "loop_depth": context.loop_depth,
                "in_loop": context.in_loop,
                "reflector_generated": context.reflector_generated,
                "half_point_depth": _DEPTH_HALF,
            },
            ", ".join(structure_notes),
        )
    )

    # --- keywords --------------------------------------------------------
    description = _get(definition, "description", "")
    haystack = "\n".join(
        part
        for part in (
            rendered_prompt if mode == "rendered" else template,
            description if isinstance(description, str) else "",
        )
        if part
    )
    matches = _match_keywords(haystack, table)
    keyword_normal = _clamp01(sum(weight for _, weight in matches))
    measured.append(
        (
            "keywords",
            float(len(matches)),
            keyword_normal,
            False,
            {
                "matched": {phrase: weight for phrase, weight in matches},
                "table_size": len(table),
                "source": "rendered_prompt" if mode == "rendered" else "template",
            },
            (
                f"matched {', '.join(phrase for phrase, _ in matches)}"
                if matches
                else "no keyword matches"
            ),
        )
    )

    return _assemble(
        measured=measured,
        weights=resolved_weights,
        mode=mode,
        warnings=warnings,
    )


def _assemble(
    *,
    measured: Iterable[tuple[str, float, float, bool, dict[str, Any], str]],
    weights: Mapping[str, float],
    mode: ScoreMode,
    warnings: list[str],
) -> ComplexityScore:
    """Turn raw measurements into weighted contributions and a total.

    Split out from :func:`score` so the weighted-mean arithmetic lives in one
    place: contributions are computed once, and the total is their sum rather
    than an independently-derived number that could drift from the breakdown.
    """
    entries = list(measured)
    # Round the inputs to the arithmetic *before* using them, and derive the
    # total from the rounded contributions. A reader adding up the reported
    # numbers then gets the reported total exactly, instead of a value that
    # differs in the last place because the scorer used more precision than it
    # printed.
    weight_total = _round(
        sum(max(0.0, _round(_number(weights.get(name, 0.0)))) for name, *_ in entries)
    )

    if weight_total <= 0:
        warnings.append(
            "weights: every weight is zero; score is 0 and no signal contributes."
        )

    signals: list[SignalScore] = []
    total = 0.0
    for name, raw, normalized, estimated, detail, note in entries:
        weight = max(0.0, _round(_number(weights.get(name, 0.0))))
        normalized = _round(_clamp01(normalized))
        contribution = (
            0.0 if weight_total <= 0 else MAX_SCORE * weight * normalized / weight_total
        )
        contribution = _round(contribution)
        total += contribution
        signals.append(
            SignalScore(
                name=name,
                raw=_round(raw),
                normalized=normalized,
                weight=weight,
                contribution=contribution,
                estimated=estimated,
                detail=detail,
                note=note,
            )
        )

    return ComplexityScore(
        score=_round(min(MAX_SCORE, max(MIN_SCORE, total))),
        mode=mode,
        estimated=any(s.estimated for s in signals),
        signals=tuple(signals),
        weight_total=_round(weight_total),
        warnings=tuple(warnings),
    )
