#!/usr/bin/env python3
"""Copy Circuitry's tool-plugin registry's name list into electricity-tools.

``plugins/factory.py::build_plugin``'s own "Unknown plugin: ... Supported
plugins: ..." text lists Python's *full* registry (every provider name in
``PLUGIN_REGISTRY``, sorted), not just the handful electricity itself can
build. electricity-tools's own builder (``registry.rs::build_plugin``) needs
that exact list to word its own unknown-plugin message the same way, even for
a provider name no electricity lane has implemented yet -- the message is
only ever the reason a `tool` effect's `provider:` is refused, never a
dispatch decision, so it must speak to "every provider Circuitry itself
knows", not "every provider electricity knows".

Usage: python3 generate_plugin_names.py [--check]
"""

from __future__ import annotations

import sys
from pathlib import Path

from circuitry.plugins.factory import PLUGIN_REGISTRY

OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "crates"
    / "electricity-tools"
    / "src"
    / "plugin_names.rs"
)

_HEADER = """\
//! @generated by `electricity/scripts/generate_plugin_names.py --check`.
//! Do not edit by hand -- it copies `plugins/factory.py::PLUGIN_REGISTRY`'s
//! own key set, sorted, into this crate so `registry::build_plugin`'s own
//! unknown-plugin message lists Python's full registry (issue #449's gate
//! lane, item 2).
"""


def render() -> str:
    names = sorted(PLUGIN_REGISTRY.keys())
    lines = [_HEADER, "pub const PLUGIN_NAMES: &[&str] = &["]
    lines.extend(f'    "{name}",' for name in names)
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    data = render().encode("utf-8")
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    if "--check" in sys.argv[1:]:
        current = OUTPUT.read_bytes() if OUTPUT.exists() else b""
        if current != data:
            print(f"{OUTPUT} is stale; run without --check to regenerate", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_bytes(data)
    print(f"wrote {OUTPUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
