#!/usr/bin/env python3
"""Generate the non-printable Unicode codepoint ranges `str.isprintable()` uses.

Python defines "printable" as: not categorized as "Other" (Cc, Cf, Cs, Co,
Cn) or "Separator" (Zl, Zp, Zs) in the Unicode Character Database, except the
ASCII space (U+0020), which counts as printable. `str.repr()` escapes every
non-printable character.

electricity-value needs this exact table to match CPython's `repr()` byte
for byte (DESIGN.md §3.1). Rather than depend on a Unicode-category crate
pinned to whatever Unicode version it last shipped with (a real parity risk:
Python 3.11 ships Unicode 14.0.0, and a newer crate may classify
newly-assigned codepoints differently), this script reads the answer
directly from the interpreter generating electricity's golden corpus, and
writes it into the crate as generated, checked-in Rust source. Must be run
with the same Python version/Unicode Character Database version used to
generate the golden corpus (see generate_value_corpus.py) -- CI and the lane
venv both pin Python 3.11.

Usage: python3 generate_unicode_printable_ranges.py
Writes: crates/electricity-value/src/generated/unicode_nonprintable_ranges.rs
"""

from __future__ import annotations

import sys
import unicodedata
from pathlib import Path

OUTPUT = (
    Path(__file__).resolve().parent.parent
    / "crates"
    / "electricity-value"
    / "src"
    / "generated"
    / "unicode_nonprintable_ranges.rs"
)

NONPRINTABLE_CATEGORIES = {"Cc", "Cf", "Cs", "Co", "Cn", "Zl", "Zp", "Zs"}


def nonprintable_ranges() -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    for cp in range(0x110000):
        is_nonprintable = (
            cp != 0x20 and unicodedata.category(chr(cp)) in NONPRINTABLE_CATEGORIES
        )
        if is_nonprintable and start is None:
            start = cp
        elif not is_nonprintable and start is not None:
            ranges.append((start, cp - 1))
            start = None
    if start is not None:
        ranges.append((start, 0x10FFFF))
    return ranges


def render(ranges: list[tuple[int, int]]) -> str:
    lines = [f"    (0x{lo:X}, 0x{hi:X})," for lo, hi in ranges]
    body = "\n".join(lines)
    return f"""\
//! Generated by `electricity/scripts/generate_unicode_printable_ranges.py`.
//! Do not hand-edit; re-run the script instead.
//!
//! Inclusive `(low, high)` codepoint ranges that are *not* printable per
//! Python's `str.isprintable()` (Unicode category Cc/Cf/Cs/Co/Cn/Zl/Zp/Zs,
//! except the ASCII space), generated against the Unicode Character
//! Database version the script's Python interpreter ships.
//!
//! Unicode Character Database version: {unicodedata.unidata_version}.

pub(crate) const NONPRINTABLE_RANGES: &[(u32, u32)] = &[
{body}
];
"""


def main() -> int:
    ranges = nonprintable_ranges()
    text = render(ranges)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    if "--check" in sys.argv[1:]:
        current = OUTPUT.read_text() if OUTPUT.exists() else ""
        if current != text:
            print(f"{OUTPUT} is stale; run without --check to regenerate", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(text)
    print(f"wrote {OUTPUT} ({len(ranges)} ranges)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
