//! Replays the golden corpus generated by
//! `electricity/scripts/generate_config_corpus.py` against this crate's
//! `resolve_config`, `effective_settings`, `validate_complexity` and
//! `validate_persistence`.
//!
//! The corpus is checked in (`tests/golden/config_corpus.json`); CI
//! separately regenerates it with Python 3.11 from Circuitry's own
//! `cli.config`/`cli.effective_settings`/`cli.complexity_config`/
//! `core.store.persistence` and fails the build if it differs
//! (`.github/workflows/electricity-generated.yml`), so this test only
//! needs to trust the committed file.

use electricity_config::{
    CircuitryConfig, resolve_config, validate_complexity, validate_persistence,
};
use electricity_value::{Dict, Value};
use std::collections::HashMap;
use std::fs;
use std::path::Path;

fn load_corpus() -> Vec<Value> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/golden/config_corpus.json");
    let text = fs::read_to_string(&path).expect("golden/config_corpus.json must exist");
    let value = electricity_json::loads(&text).expect("golden corpus must be valid JSON");
    match &value {
        Value::List(cases) => cases.clone(),
        other => panic!("expected a JSON array of cases, got {other:?}"),
    }
}

fn get<'a>(dict: &'a Dict, key: &str) -> Option<&'a Value> {
    dict.get(&Value::Str(key.to_string()))
}

fn s(dict: &Dict, key: &str) -> String {
    get(dict, key)
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("missing string field {key:?}"))
        .to_string()
}

fn case_dict(case: &Value) -> &Dict {
    case.as_dict().expect("each case must be an object")
}

fn string_map(value: Option<&Value>) -> HashMap<String, String> {
    let Some(Value::Dict(dict)) = value else {
        return HashMap::new();
    };
    dict.iter()
        .map(|(k, v)| (k.py_str(), v.as_str().unwrap_or_default().to_string()))
        .collect()
}

/// A fresh scratch directory under the OS temp dir, matching every other
/// Rust test in this workspace (no `tempfile` dependency).
struct ScratchRoot(std::path::PathBuf);

impl ScratchRoot {
    fn new(tag: &str) -> Self {
        let dir = std::env::temp_dir().join(format!(
            "electricity-config-golden-{tag}-{}-{:?}",
            std::process::id(),
            std::thread::current().id()
        ));
        fs::create_dir_all(&dir).unwrap();
        ScratchRoot(dir)
    }
}

impl Drop for ScratchRoot {
    fn drop(&mut self) {
        let _ = fs::remove_dir_all(&self.0);
    }
}

fn run_resolve_config_case(case: &Dict, root: &Path) {
    let name = s(case, "name");
    let input = get(case, "input")
        .and_then(Value::as_dict)
        .expect("resolve_config case needs input");
    let expect = get(case, "expect").and_then(Value::as_dict).unwrap();

    let case_dir = root.join(&name);
    fs::create_dir_all(&case_dir).unwrap();

    let is_directory = get(input, "is_directory")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let path_through_file = get(input, "path_through_file")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let invalid_utf8 = get(input, "invalid_utf8")
        .and_then(Value::as_bool)
        .unwrap_or(false);
    let file_text = get(input, "file_text").and_then(Value::as_str);

    let config_path = if path_through_file {
        let not_a_dir = case_dir.join("not_a_directory");
        fs::write(&not_a_dir, "").unwrap();
        not_a_dir.join("config.json")
    } else {
        let config_path = case_dir.join("config.json");
        if invalid_utf8 {
            fs::write(&config_path, [b'{', b'"', 0xff, 0xfe, b'"', b'}']).unwrap();
        } else if is_directory {
            fs::create_dir_all(&config_path).unwrap();
        } else if let Some(text) = file_text {
            fs::write(&config_path, text).unwrap();
        }
        config_path
    };

    let env = string_map(get(input, "env"));

    let result = resolve_config(&config_path, &env);
    let expect_ok = get(expect, "ok").and_then(Value::as_bool).unwrap();
    let root_str = root.to_string_lossy().into_owned();

    match (result, expect_ok) {
        (Ok(cfg), true) => {
            let expected_config = get(expect, "config").and_then(Value::as_dict).unwrap();
            assert_eq!(
                cfg.default_model,
                get(expected_config, "default_model")
                    .and_then(Value::as_str)
                    .map(str::to_string),
                "case {name}: default_model"
            );
            assert_eq!(
                cfg.default_adapter,
                get(expected_config, "default_adapter")
                    .and_then(Value::as_str)
                    .map(str::to_string),
                "case {name}: default_adapter"
            );
            assert_eq!(
                cfg.environment,
                s(expected_config, "environment"),
                "case {name}: environment"
            );
            assert_eq!(
                cfg.enabled_adapters,
                decode_opt_str_list(get(expected_config, "enabled_adapters")),
                "case {name}: enabled_adapters"
            );
            assert_eq!(
                cfg.enabled_plugins,
                decode_opt_str_list(get(expected_config, "enabled_plugins")),
                "case {name}: enabled_plugins"
            );
            assert_eq!(
                cfg.enabled_tools,
                decode_opt_str_list(get(expected_config, "enabled_tools")),
                "case {name}: enabled_tools"
            );
            let expected_runtime = get(expected_config, "runtime").cloned();
            assert_eq!(cfg.runtime, expected_runtime, "case {name}: runtime");
        }
        (Err(err), false) => {
            let expected_error = s(expect, "error").replace("<root>", &root_str);
            assert_eq!(err.0, expected_error, "case {name}: error text");
        }
        (Ok(_), false) => panic!("case {name}: expected an error, resolve_config succeeded"),
        (Err(err), true) => panic!("case {name}: expected success, got error {err:?}"),
    }
}

fn decode_opt_str_list(value: Option<&Value>) -> Option<Vec<String>> {
    match value {
        None | Some(Value::None) => None,
        Some(Value::List(items)) => Some(
            items
                .iter()
                .map(|v| v.as_str().unwrap_or_default().to_string())
                .collect(),
        ),
        _ => None,
    }
}

fn config_from_corpus(value: &Value) -> CircuitryConfig {
    let dict = value.as_dict().expect("config input must be an object");
    CircuitryConfig {
        default_model: get(dict, "default_model")
            .and_then(Value::as_str)
            .map(str::to_string),
        default_adapter: get(dict, "default_adapter")
            .and_then(Value::as_str)
            .map(str::to_string),
        plugins: get(dict, "plugins")
            .and_then(Value::as_list)
            .map(<[Value]>::to_vec)
            .unwrap_or_default(),
        enabled_adapters: decode_opt_str_list(get(dict, "enabled_adapters")),
        enabled_plugins: decode_opt_str_list(get(dict, "enabled_plugins")),
        enabled_tools: decode_opt_str_list(get(dict, "enabled_tools")),
        environment: get(dict, "environment")
            .and_then(Value::as_str)
            .unwrap_or("dev")
            .to_string(),
        runtime: get(dict, "runtime").cloned(),
    }
}

fn run_effective_settings_case(case: &Dict) {
    let name = s(case, "name");
    let input = get(case, "input")
        .and_then(Value::as_dict)
        .expect("effective_settings case needs input");
    let expect = get(case, "expect").and_then(Value::as_dict).unwrap();

    let config = config_from_corpus(get(input, "config").unwrap());
    let orch = get(input, "orch").unwrap().clone();
    let document_name = get(input, "document_name").and_then(Value::as_str);

    let result = electricity_config::effective_settings(&config, &orch, document_name);
    let expect_ok = get(expect, "ok").and_then(Value::as_bool).unwrap();

    match (result, expect_ok) {
        (Ok(settings), true) => {
            assert_eq!(
                settings.model,
                get(expect, "model")
                    .and_then(Value::as_str)
                    .map(str::to_string),
                "case {name}: model"
            );
            assert_eq!(
                settings.adapter,
                get(expect, "adapter")
                    .and_then(Value::as_str)
                    .map(str::to_string),
                "case {name}: adapter"
            );
            let expected_plugins = get(expect, "plugins")
                .and_then(Value::as_list)
                .map(<[Value]>::to_vec)
                .unwrap_or_default();
            assert_eq!(settings.plugins, expected_plugins, "case {name}: plugins");
            let expected_runtime = get(expect, "runtime")
                .cloned()
                .unwrap_or(Value::Dict(Dict::new()));
            let actual_runtime = settings.runtime.clone().unwrap_or(Value::Dict(Dict::new()));
            assert!(
                actual_runtime.py_eq(&expected_runtime),
                "case {name}: runtime differs"
            );

            let expected_sources: Vec<(String, String)> = get(expect, "sources")
                .and_then(Value::as_list)
                .unwrap_or(&[])
                .iter()
                .map(|pair| {
                    let pair = pair.as_list().unwrap();
                    (
                        pair[0].as_str().unwrap().to_string(),
                        pair[1].as_str().unwrap().to_string(),
                    )
                })
                .collect();
            let actual_sources: Vec<(String, String)> = settings
                .sources
                .iter()
                .map(|(k, v)| (k.clone(), v.clone()))
                .collect();
            assert_eq!(
                actual_sources, expected_sources,
                "case {name}: sources order/content"
            );

            let expected_warnings: Vec<String> = get(expect, "warnings")
                .and_then(Value::as_list)
                .unwrap_or(&[])
                .iter()
                .map(|w| w.as_str().unwrap().to_string())
                .collect();
            assert_eq!(
                settings.warnings, expected_warnings,
                "case {name}: warnings"
            );
        }
        (Err(err), false) => {
            assert_eq!(err.0, s(expect, "error"), "case {name}: error text");
        }
        (Ok(settings), false) => {
            panic!("case {name}: expected an error, effective_settings succeeded with {settings:?}")
        }
        (Err(err), true) => panic!("case {name}: expected success, got error {err:?}"),
    }
}

fn run_complexity_case(case: &Dict) {
    let name = s(case, "name");
    let input = get(case, "input").and_then(Value::as_dict).unwrap();
    let expect = get(case, "expect").and_then(Value::as_dict).unwrap();
    let runtime = get(input, "runtime").unwrap().clone();
    let document = Value::Dict(Dict::new());

    let result = validate_complexity(&document, Some(&runtime));
    let expect_ok = get(expect, "ok").and_then(Value::as_bool).unwrap();
    match (result, expect_ok) {
        (Ok(()), true) => {}
        (Err(err), false) => assert_eq!(err.0, s(expect, "error"), "case {name}: error text"),
        (Ok(()), false) => panic!("case {name}: expected an error, validate_complexity succeeded"),
        (Err(err), true) => panic!("case {name}: expected success, got error {err:?}"),
    }
}

fn run_persistence_case(case: &Dict) {
    let name = s(case, "name");
    let input = get(case, "input").and_then(Value::as_dict).unwrap();
    let expect = get(case, "expect").and_then(Value::as_dict).unwrap();
    let runtime = get(input, "runtime").unwrap().clone();
    let document = Value::Dict(Dict::new());

    let result = validate_persistence(&document, Some(&runtime));
    let expect_ok = get(expect, "ok").and_then(Value::as_bool).unwrap();
    match (result, expect_ok) {
        (Ok(()), true) => {}
        (Err(err), false) => assert_eq!(err.0, s(expect, "error"), "case {name}: error text"),
        (Ok(()), false) => panic!("case {name}: expected an error, validate_persistence succeeded"),
        (Err(err), true) => panic!("case {name}: expected success, got error {err:?}"),
    }
}

#[test]
fn every_case_in_the_corpus_matches_electricity_configs_own_port() {
    let corpus = load_corpus();
    assert!(!corpus.is_empty(), "corpus must not be empty");
    let root = ScratchRoot::new("resolve-config");

    let mut seen_kinds = std::collections::BTreeSet::new();
    for case in &corpus {
        let dict = case_dict(case);
        let kind = s(dict, "kind");
        seen_kinds.insert(kind.clone());
        match kind.as_str() {
            "resolve_config" => run_resolve_config_case(dict, &root.0),
            "effective_settings" => run_effective_settings_case(dict),
            "complexity" => run_complexity_case(dict),
            "persistence" => run_persistence_case(dict),
            other => panic!("unknown case kind {other:?}"),
        }
    }
    assert_eq!(
        seen_kinds,
        std::collections::BTreeSet::from([
            "resolve_config".to_string(),
            "effective_settings".to_string(),
            "complexity".to_string(),
            "persistence".to_string(),
        ]),
        "every case kind this test knows how to run should appear at least once"
    );
}
