"""``cof run --decompose-out <dir>`` — persist generated decomposition plans.

``meta.decomposition`` (see :mod:`circuitry.core.decompose`) already carries
the whole story of a decomposition attempt, YAML included; this module is
just the disk-writing side of that record; it introduces no second copy of
the decision logic. One file per effect whose decomposition attempt actually
produced an orchestration document — a planner failure or a depth-ceiling
route-up never reaches the planner, so there is nothing to write for those.

A written file is the planner's emitted YAML verbatim, headed by a comment
block naming the run, the effect, and the outcome. The YAML the planner
returns is already just the orchestration document (chunk effects and a
merge) — it carries no run state or secrets, so nothing here needs to redact
anything.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from pathlib import Path
from typing import Any

#: Anything outside this set becomes '-' in a filename component, so a run ID
#: or an effect path with dots/colons/slashes still yields one clean segment.
_UNSAFE_CHARS = re.compile(r"[^A-Za-z0-9._-]+")


def _sanitize(text: str) -> str:
    cleaned = _UNSAFE_CHARS.sub("-", text).strip("-")
    return cleaned or "effect"


def plan_filename(run_id: str, effect_path: str) -> str:
    """Deterministic, collision-free filename for one effect's plan.

    ``run_id`` is unique per run and ``effect_path`` is the canonical dotted
    path :meth:`circuitry.core.store.Store.effect_path` assigns — unique
    within a run even across loop iterations and nested decomposition
    children — so the pair never collides across effects or runs.
    """
    return f"{_sanitize(run_id)}__{_sanitize(effect_path)}.yml"


def _header(*, run_id: str, effect_path: str, decomposition: dict[str, Any]) -> str:
    def _line(text: Any) -> str:
        # Comment lines can't carry embedded newlines without breaking the
        # rest of the line out of the comment.
        return str(text).replace("\n", " ").replace("\r", " ")

    status = "succeeded" if decomposition.get("decomposed") else "failed"
    lines = [
        "# Generated by circuitry decomposition — cof run --decompose-out",
        f"# run_id: {_line(run_id)}",
        f"# effect: {_line(effect_path)}",
        f"# status: {status}",
        f"# reason: {_line(decomposition.get('reason') or 'none')}",
        f"# result_path: {_line(decomposition.get('result_path') or '')}",
        f"# chunk_count: {_line(decomposition.get('chunk_count'))}",
    ]
    error = decomposition.get("error")
    if error:
        lines.append(f"# error: {_line(error)}")
    return "\n".join(lines) + "\n"


def write_decomposition_plan(
    out_dir: Path,
    *,
    run_id: str,
    effect_path: str,
    decomposition: dict[str, Any],
) -> Path | None:
    """Write one effect's generated plan under *out_dir*.

    Returns the written path, or ``None`` when there is nothing to write —
    the attempt never reached a planner-emitted document (``max_depth`` or
    ``planner_failed``). A plan that failed validation or child execution
    still has YAML worth reading and is written, headed ``status: failed``.
    """
    yaml_text = decomposition.get("yaml")
    if not isinstance(yaml_text, str) or not yaml_text.strip():
        return None

    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / plan_filename(run_id, effect_path)
    header = _header(run_id=run_id, effect_path=effect_path, decomposition=decomposition)
    path.write_text(header + yaml_text.rstrip("\n") + "\n", encoding="utf-8")
    return path


def make_decompose_out_observer(
    out_dir: Path, run_id: str
) -> Callable[[str, dict[str, Any]], None]:
    """An ``effect_observer`` (see ``RunRequest.effect_observer``) that writes
    every effect's triggered decomposition plan to *out_dir* as it lands."""

    def _observe(effect_path: str, effect_node: dict[str, Any]) -> None:
        meta = effect_node.get("meta")
        if not isinstance(meta, dict):
            return
        decomposition = meta.get("decomposition")
        if not isinstance(decomposition, dict):
            return
        write_decomposition_plan(
            out_dir,
            run_id=run_id,
            effect_path=effect_path,
            decomposition=decomposition,
        )

    return _observe
