"""``cof run --decompose-out <dir>`` — persist generated decomposition plans.

``meta.decomposition`` (see :mod:`circuitry.core.decompose`) already carries
the whole story of a decomposition attempt, YAML included; this module is
just the disk-writing side of that record; it introduces no second copy of
the decision logic. One file per effect whose decomposition attempt actually
produced a document worth reading — a depth-ceiling route-up never calls the
planner at all, so there is nothing to write for that; a planner failure
still writes the rejected payload when the planner returned one (schema
violation), and writes nothing when it truly did not (timeout, adapter
error).

A written file is the planner's output verbatim, headed by a comment block
naming the run, the effect, and the outcome. That output — either the
emitted orchestration YAML, or the raw payload a schema rejected — carries no
run state or secrets, so nothing here needs to redact anything.
"""

from __future__ import annotations

import re
from collections.abc import Callable
from pathlib import Path
from typing import Any

#: Anything outside this set becomes '-' in a filename component, so a run ID
#: or an effect path with dots/colons/slashes still yields one clean segment.
_UNSAFE_CHARS = re.compile(r"[^A-Za-z0-9._-]+")


def _sanitize(text: str) -> str:
    cleaned = _UNSAFE_CHARS.sub("-", text).strip("-")
    return cleaned or "effect"


def plan_filename(run_id: str, effect_path: str) -> str:
    """Deterministic, collision-free filename for one effect's plan.

    ``run_id`` is unique per run and ``effect_path`` is the canonical dotted
    path :meth:`circuitry.core.store.Store.effect_path` assigns — unique
    within a run even across loop iterations and nested decomposition
    children — so the pair never collides across effects or runs.
    """
    return f"{_sanitize(run_id)}__{_sanitize(effect_path)}.yml"


def _rejected_filename(run_id: str, effect_path: str, *, parses_as_data: bool) -> str:
    """Filename for a planner payload that failed the envelope schema.

    Same ``<run>__<effect>`` stem as :func:`plan_filename`, marked
    ``.rejected`` so it never collides with a succeeded/invalid-plan write for
    the same effect, and suffixed ``.yml`` or ``.txt`` by whether the payload
    happens to parse as YAML/JSON — a readability hint only; the content
    written is the raw text either way.
    """
    suffix = "yml" if parses_as_data else "txt"
    return f"{_sanitize(run_id)}__{_sanitize(effect_path)}.rejected.{suffix}"


def _parses_as_data(text: str) -> bool:
    import yaml as _yaml

    try:
        _yaml.safe_load(text)
    except _yaml.YAMLError:
        return False
    return True


def _header(*, run_id: str, effect_path: str, decomposition: dict[str, Any]) -> str:
    def _line(text: Any) -> str:
        # Comment lines can't carry embedded newlines without breaking the
        # rest of the line out of the comment.
        return str(text).replace("\n", " ").replace("\r", " ")

    status = "succeeded" if decomposition.get("decomposed") else "failed"
    lines = [
        "# Generated by circuitry decomposition — cof run --decompose-out",
        f"# run_id: {_line(run_id)}",
        f"# effect: {_line(effect_path)}",
        f"# status: {status}",
        f"# reason: {_line(decomposition.get('reason') or 'none')}",
        f"# result_path: {_line(decomposition.get('result_path') or '')}",
        f"# chunk_count: {_line(decomposition.get('chunk_count'))}",
    ]
    error = decomposition.get("error")
    if error:
        lines.append(f"# error: {_line(error)}")
    return "\n".join(lines) + "\n"


def write_decomposition_plan(
    out_dir: Path,
    *,
    run_id: str,
    effect_path: str,
    decomposition: dict[str, Any],
) -> Path | None:
    """Write one effect's generated plan under *out_dir*.

    Returns the written path, or ``None`` when there is nothing to write. A
    plan that failed validation or child execution still has YAML worth
    reading and is written, headed ``status: failed``. A planner failure
    (``planner_failed``) writes the rejected raw payload the same way when
    the planner returned one — a schema violation, not silence — and writes
    nothing when it did not (timeout, adapter error) or when the depth
    ceiling routed up without ever calling the planner (``max_depth``).
    """
    yaml_text = decomposition.get("yaml")
    if isinstance(yaml_text, str) and yaml_text.strip():
        out_dir.mkdir(parents=True, exist_ok=True)
        path = out_dir / plan_filename(run_id, effect_path)
        header = _header(run_id=run_id, effect_path=effect_path, decomposition=decomposition)
        path.write_text(header + yaml_text.rstrip("\n") + "\n", encoding="utf-8")
        return path

    if decomposition.get("reason") != "planner_failed":
        return None
    raw_payload = decomposition.get("raw_payload")
    if not isinstance(raw_payload, str) or not raw_payload.strip():
        return None

    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / _rejected_filename(
        run_id, effect_path, parses_as_data=_parses_as_data(raw_payload)
    )
    header = _header(run_id=run_id, effect_path=effect_path, decomposition=decomposition)
    path.write_text(header + raw_payload.rstrip("\n") + "\n", encoding="utf-8")
    return path


def make_decompose_out_observer(
    out_dir: Path, run_id: str
) -> Callable[[str, dict[str, Any]], None]:
    """An ``effect_observer`` (see ``RunRequest.effect_observer``) that writes
    every effect's triggered decomposition plan to *out_dir* as it lands."""

    def _observe(effect_path: str, effect_node: dict[str, Any]) -> None:
        meta = effect_node.get("meta")
        if not isinstance(meta, dict):
            return
        decomposition = meta.get("decomposition")
        if not isinstance(decomposition, dict):
            return
        write_decomposition_plan(
            out_dir,
            run_id=run_id,
            effect_path=effect_path,
            decomposition=decomposition,
        )

    return _observe
