//! Replays the golden corpus generated by
//! `electricity/scripts/generate_tool_runtime_corpus.py` -- real output
//! from Circuitry's own `JsonPlugin.execute` (`plugins/json.py`) --
//! against this crate's `JsonTool`.
//!
//! The corpus is checked in (`tests/golden/json_tool_corpus.json`); CI
//! separately regenerates it with Python 3.11 and fails the build if it
//! differs (`.github/workflows/electricity-generated.yml`), so this test
//! only needs to trust the committed file.

use electricity_tools::{ToolPlugin, json::JsonTool};
use electricity_value::{Dict, Value};
use serde::Deserialize;

#[derive(Deserialize, Debug)]
#[serde(tag = "t")]
enum TaggedValue {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "bool")]
    Bool { v: bool },
    #[serde(rename = "int")]
    Int { v: String },
    #[serde(rename = "float")]
    Float { bits: String },
    #[serde(rename = "str")]
    Str { v: String },
    #[serde(rename = "list")]
    List { v: Vec<TaggedValue> },
    #[serde(rename = "dict")]
    Dict { v: Vec<(TaggedValue, TaggedValue)> },
}

impl From<TaggedValue> for Value {
    fn from(tagged: TaggedValue) -> Self {
        match tagged {
            TaggedValue::None => Value::None,
            TaggedValue::Bool { v } => Value::Bool(v),
            TaggedValue::Int { v } => Value::Int(
                electricity_value::IntValue::parse_decimal(&v).expect("valid decimal integer"),
            ),
            TaggedValue::Float { bits } => {
                let bits = u64::from_str_radix(&bits, 16).expect("valid hex bit pattern");
                Value::Float(f64::from_bits(bits))
            }
            TaggedValue::Str { v } => Value::Str(v),
            TaggedValue::List { v } => Value::List(v.into_iter().map(Value::from).collect()),
            TaggedValue::Dict { v } => {
                let mut dict = Dict::new();
                for (k, val) in v {
                    dict.insert(Value::from(k), Value::from(val));
                }
                Value::Dict(dict)
            }
        }
    }
}

#[derive(Deserialize)]
struct JsonToolCase {
    params: TaggedValue,
    ok: Option<TaggedValue>,
    raw: Option<TaggedValue>,
    err: Option<String>,
    /// Circuitry's own exact text in front of a wrapped
    /// `json.JSONDecodeError` (`None` when [`JsonToolCase::err`] is
    /// `Some`, i.e. not a decode-error case).
    err_prefix: Option<String>,
    /// The matching `json.JSONDecodeError.pos`; electricity's own
    /// decode error only has to fail at this same character offset
    /// (DESIGN.md §1/§12), not match the third-party message text.
    err_char: Option<i64>,
}

#[derive(Deserialize)]
struct Corpus {
    json_tool_cases: Vec<JsonToolCase>,
}

#[tokio::test]
async fn golden_corpus_json_tool() {
    let text = include_str!("golden/json_tool_corpus.json");
    let corpus: Corpus =
        serde_json::from_str(text).expect("golden/json_tool_corpus.json is valid JSON");
    assert!(!corpus.json_tool_cases.is_empty());

    let tool = JsonTool;
    let mut failures = Vec::new();
    for (i, case) in corpus
        .json_tool_cases
        .into_iter()
        .enumerate()
        // Decode-error cases (`err_prefix` set) are covered separately,
        // by `golden_corpus_json_tool_decode_error_position` below --
        // their third-party tail only has to fail at the same position,
        // never match Circuitry's recorded `err` text exactly.
        .filter(|(_, case)| case.err_prefix.is_none())
    {
        let params = Value::from(case.params);
        let result = tool.execute(params.clone(), 30).await;
        match (result, case.ok, case.raw, case.err) {
            (Ok(got), Some(ok), Some(raw), None) => {
                let expected_value = Value::from(ok);
                let expected_raw = Value::from(raw);
                if got.value != expected_value || got.raw != expected_raw {
                    failures.push(format!(
                        "case {i} ({params:?}): expected value={expected_value:?} raw={expected_raw:?}, got value={:?} raw={:?}",
                        got.value, got.raw
                    ));
                }
            }
            (Err(err), None, None, Some(expected)) => {
                if err.0 != expected {
                    failures.push(format!(
                        "case {i} ({params:?}): expected err {expected:?}, got {:?}",
                        err.0
                    ));
                }
            }
            (got, expected_ok, expected_raw, expected_err) => failures.push(format!(
                "case {i} ({params:?}): expected ok={expected_ok:?} raw={expected_raw:?} err={expected_err:?}, got {:?}",
                got.map(|r| (r.value, r.raw))
            )),
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

/// Cases whose expected failure wraps a `json.JSONDecodeError`: only
/// Circuitry's own prefix has to match exactly; the third-party tail
/// only has to fail at the same character offset (DESIGN.md §1/§12),
/// via electricity-json's own `"{message}: char {pos}"` Display.
#[tokio::test]
async fn golden_corpus_json_tool_decode_error_position() {
    let text = include_str!("golden/json_tool_corpus.json");
    let corpus: Corpus =
        serde_json::from_str(text).expect("golden/json_tool_corpus.json is valid JSON");
    let decode_cases: Vec<_> = corpus
        .json_tool_cases
        .into_iter()
        .filter(|c| c.err_prefix.is_some())
        .collect();
    assert!(!decode_cases.is_empty());

    let tool = JsonTool;
    let mut failures = Vec::new();
    for (i, case) in decode_cases.into_iter().enumerate() {
        let params = Value::from(case.params);
        let prefix = case.err_prefix.expect("filtered above");
        let expected_char = case.err_char.expect("present alongside err_prefix");
        let Err(err) = tool.execute(params.clone(), 30).await else {
            failures.push(format!(
                "decode case {i} ({params:?}): expected an error, got Ok"
            ));
            continue;
        };
        let got_char: Option<i64> = err
            .0
            .rsplit("char ")
            .next()
            .and_then(|tail| tail.parse().ok());
        if !err.0.starts_with(&prefix) || got_char != Some(expected_char) {
            failures.push(format!(
                "decode case {i} ({params:?}): expected prefix {prefix:?} and char {expected_char}, got {:?}",
                err.0
            ));
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
