//! Replays the golden corpus generated by
//! `electricity/scripts/generate_yaml_corpus.py` against
//! [`electricity_yaml::load_yaml`].
//!
//! The corpus is checked in (`tests/golden/corpus.json`); CI separately
//! regenerates it with Python 3.11 and fails the build if it differs
//! (`.github/workflows/electricity-generated.yml`), so this test only
//! needs to trust the committed file.

use electricity_yaml::{YamlError, load_yaml};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
enum Expected {
    Value {
        repr: String,
    },
    DuplicateKeyError {
        message: String,
    },
    Error {
        line: Option<usize>,
        column: Option<usize>,
        /// Set only on a non-ASCII variant (`generate_yaml_corpus.py`'s
        /// `non_ascii_variants`), to its originating case's own index in
        /// this same array -- always earlier, since `build_corpus` appends
        /// every variant after the whole base list. See the main loop's
        /// own comment for why a variant is checked against that case's
        /// *own* column drift rather than directly against `column`.
        #[serde(default)]
        original_index: Option<usize>,
    },
    KnownDivergence {
        #[allow(dead_code)]
        python_repr: String,
        rust_error_tag: Option<String>,
        rust_error_contains: Option<String>,
    },
}

#[derive(Deserialize)]
struct Case {
    yaml: String,
    #[serde(flatten)]
    expected: Expected,
}

#[test]
fn golden_corpus() {
    let text = include_str!("golden/corpus.json");
    let cases: Vec<Case> = serde_json::from_str(text).expect("golden/corpus.json is valid JSON");
    assert!(!cases.is_empty(), "golden corpus must not be empty");

    // `diffs[i]`, once case `i` has been checked: `mark.column as i64 -
    // column as i64` when the error's line matched and both sides carry
    // a column, `None` otherwise -- a variant's own comparison below
    // looks its original case up here (always at a lower index, so
    // always already filled in by the time the variant is reached).
    let mut diffs: Vec<Option<i64>> = Vec::with_capacity(cases.len());
    let mut failures = Vec::new();
    for (i, case) in cases.iter().enumerate() {
        let result = load_yaml(&case.yaml);
        let mut own_diff = None;
        match &case.expected {
            Expected::Value { repr } => match result {
                Ok(value) if value.py_repr() == *repr => {}
                Ok(value) => failures.push(format!(
                    "case {i} ({:?}): expected value {repr:?}, got {:?}",
                    case.yaml,
                    value.py_repr()
                )),
                Err(e) => failures.push(format!(
                    "case {i} ({:?}): expected value {repr:?}, got error {e}",
                    case.yaml
                )),
            },
            Expected::DuplicateKeyError { message } => match result {
                Err(YamlError::DuplicateKey { message: got }) if got == *message => {}
                Err(YamlError::DuplicateKey { message: got }) => failures.push(format!(
                    "case {i} ({:?}): duplicate-key message mismatch:\n  expected {message:?}\n  got      {got:?}",
                    case.yaml
                )),
                Ok(value) => failures.push(format!(
                    "case {i} ({:?}): expected a DuplicateKeyError, got value {:?}",
                    case.yaml,
                    value.py_repr()
                )),
                Err(other) => failures.push(format!(
                    "case {i} ({:?}): expected a DuplicateKeyError, got {other}",
                    case.yaml
                )),
            },
            Expected::Error { line, column, original_index } => match result {
                // "Same line/column *region*", not an exact column: PyYAML
                // sometimes marks the tag token, sometimes the resolved
                // scalar text, for what is -- either way -- a third-party
                // failure that only needs a non-empty message at the same
                // place (DESIGN.md §1, §12). The line must match exactly;
                // the column may drift a little (a scanner-level
                // 1.1-vs-1.2 tokenizing difference, e.g. a tab's exact
                // reported width), so it's checked within a small
                // tolerance rather than not at all.
                Err(e) => {
                    if let Some(line) = line {
                        match e.mark() {
                            Some(mark) if mark.line == *line => {
                                if let Some(column) = column {
                                    let diff = mark.column as i64 - *column as i64;
                                    own_diff = Some(diff);
                                    match original_index.and_then(|idx| diffs[idx]) {
                                        // A non-ASCII variant
                                        // (`generate_yaml_corpus.py`'s
                                        // `non_ascii_variants`) is compared
                                        // against its *own* originating case's
                                        // drift, not directly against `column`:
                                        // the two transforms (prepending a
                                        // one-line comment, widening a key's
                                        // name) never change a legitimate,
                                        // pre-existing third-party drift (a
                                        // scanner marking a different token --
                                        // confirmed above this still allows
                                        // that), only ever add a *new* one if
                                        // this crate's own column math ever
                                        // counts a 2-/3-/4-byte character by
                                        // its UTF-8 byte width instead of as
                                        // one character. Exact, never the
                                        // tolerance below: that tolerance
                                        // exists for the baseline drift itself,
                                        // already allowed once, not for
                                        // whatever a non-ASCII transform adds
                                        // on top of it.
                                        Some(original_diff) if diff != original_diff => {
                                            failures.push(format!(
                                                "case {i} ({:?}): non-ASCII variant's column drift ({diff}) doesn't match its originating case's own drift ({original_diff}) -- got column {} ({e})",
                                                case.yaml, mark.column
                                            ));
                                        }
                                        Some(_) => {}
                                        None => {
                                            let abs_diff = diff.unsigned_abs();
                                            if abs_diff > 2 {
                                                failures.push(format!(
                                                    "case {i} ({:?}): error column mismatch: expected column {column} (\u{00b1}2), got column {} ({e})",
                                                    case.yaml, mark.column
                                                ));
                                            }
                                        }
                                    }
                                }
                            }
                            Some(mark) => failures.push(format!(
                                "case {i} ({:?}): error line mismatch: expected line {line}, got line {} ({e})",
                                case.yaml, mark.line
                            )),
                            None => failures.push(format!(
                                "case {i} ({:?}): expected a position (line {line}), error carries none ({e})",
                                case.yaml
                            )),
                        }
                    }
                    // `line` (and `column`) both `None` means the real
                    // loader's exception carried no mark either (a raw
                    // `ValueError`/`KeyError`): only "it errors" is checked.
                }
                Ok(value) => failures.push(format!(
                    "case {i} ({:?}): expected an error, got value {:?}",
                    case.yaml,
                    value.py_repr()
                )),
            },
            Expected::KnownDivergence { rust_error_tag, rust_error_contains, .. } => {
                let matched = match &result {
                    Err(YamlError::UnresolvableTag { tag, .. }) => {
                        rust_error_tag.as_deref() == Some(tag.as_str())
                    }
                    Err(other) => rust_error_contains
                        .as_deref()
                        .is_some_and(|needle| other.to_string().contains(needle)),
                    Ok(_) => false,
                };
                if !matched {
                    match result {
                        Err(other) => failures.push(format!(
                            "case {i} ({:?}): expected error tag {rust_error_tag:?} / message containing {rust_error_contains:?}, got {other}",
                            case.yaml
                        )),
                        Ok(value) => failures.push(format!(
                            "case {i} ({:?}): expected a documented-divergence error, got value {:?} \
                             (electricity-yaml newly supports this -- update the generator's \
                             `known_divergence_cases` and this test)",
                            case.yaml,
                            value.py_repr()
                        )),
                    }
                }
            }
        }
        diffs.push(own_diff);
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
