//! Replays the golden corpus generated by
//! `electricity/scripts/generate_value_corpus.py` against `py_str`/`py_repr`.
//!
//! The corpus is checked in (`tests/golden/corpus.json`); CI separately
//! regenerates it with Python 3.11 and fails the build if it differs
//! (`.github/workflows/electricity.yml`), so this test only needs to trust
//! the committed file.

use chrono::{FixedOffset, NaiveDate, NaiveDateTime};
use electricity_value::{Dict, IntValue, Value};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(tag = "t")]
enum TaggedValue {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "bool")]
    Bool { v: bool },
    #[serde(rename = "int")]
    Int { v: String },
    #[serde(rename = "float")]
    Float { bits: String },
    #[serde(rename = "str")]
    Str { v: String },
    #[serde(rename = "bytes")]
    Bytes { v: String },
    #[serde(rename = "list")]
    List { v: Vec<TaggedValue> },
    #[serde(rename = "dict")]
    Dict { v: Vec<(TaggedValue, TaggedValue)> },
    #[serde(rename = "date")]
    Date { v: String },
    #[serde(rename = "datetime")]
    DateTime {
        naive: String,
        offset_seconds: Option<i64>,
    },
}

fn decode_hex(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

impl From<TaggedValue> for Value {
    fn from(tagged: TaggedValue) -> Self {
        match tagged {
            TaggedValue::None => Value::None,
            TaggedValue::Bool { v } => Value::Bool(v),
            TaggedValue::Int { v } => {
                Value::Int(IntValue::parse_decimal(&v).expect("valid decimal integer literal"))
            }
            TaggedValue::Float { bits } => {
                let bits = u64::from_str_radix(&bits, 16).expect("valid hex bit pattern");
                Value::Float(f64::from_bits(bits))
            }
            TaggedValue::Str { v } => Value::Str(v),
            TaggedValue::Bytes { v } => Value::Bytes(decode_hex(&v)),
            TaggedValue::List { v } => Value::List(v.into_iter().map(Value::from).collect()),
            TaggedValue::Dict { v } => {
                let mut dict = Dict::new();
                for (k, val) in v {
                    dict.insert(Value::from(k), Value::from(val));
                }
                Value::Dict(dict)
            }
            TaggedValue::Date { v } => {
                Value::Date(NaiveDate::parse_from_str(&v, "%Y-%m-%d").expect("valid ISO date"))
            }
            TaggedValue::DateTime {
                naive,
                offset_seconds,
            } => {
                let naive = NaiveDateTime::parse_from_str(&naive, "%Y-%m-%dT%H:%M:%S%.f")
                    .expect("valid ISO naive datetime");
                let offset = offset_seconds
                    .map(|secs| FixedOffset::east_opt(secs as i32).expect("valid UTC offset"));
                Value::DateTime(naive, offset)
            }
        }
    }
}

#[derive(Deserialize)]
struct Case {
    value: TaggedValue,
    py_str: String,
    py_repr: String,
}

#[test]
fn golden_corpus_py_str_and_py_repr() {
    let text = include_str!("golden/corpus.json");
    let cases: Vec<Case> = serde_json::from_str(text).expect("golden/corpus.json is valid JSON");
    assert!(!cases.is_empty(), "golden corpus must not be empty");

    let mut failures = Vec::new();
    for (i, case) in cases.into_iter().enumerate() {
        let value = Value::from(case.value);
        let str_got = value.py_str();
        let repr_got = value.py_repr();
        if str_got != case.py_str {
            failures.push(format!(
                "case {i}: py_str mismatch: expected {:?}, got {:?}",
                case.py_str, str_got
            ));
        }
        if repr_got != case.py_repr {
            failures.push(format!(
                "case {i}: py_repr mismatch: expected {:?}, got {:?}",
                case.py_repr, repr_got
            ));
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
