//! Replays the golden corpus generated by
//! `electricity/scripts/generate_template_corpus.py` -- real output from
//! Circuitry's own `template_syntax_error`/`render_template`
//! (`core/templates.py`) -- against this crate's port.
//!
//! The corpus is checked in (`tests/golden/corpus.json`); CI separately
//! regenerates it with Python 3.11 and fails the build if it differs
//! (`.github/workflows/electricity.yml`), so this test only needs to
//! trust the committed file.

use chrono::{FixedOffset, NaiveDate, NaiveDateTime};
use electricity_template::{JsonAwareCtx, PlainCtx, Value, render_template, template_syntax_error};
use electricity_value::Dict;
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(tag = "t")]
enum TaggedValue {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "bool")]
    Bool { v: bool },
    #[serde(rename = "int")]
    Int { v: String },
    #[serde(rename = "float")]
    Float { bits: String },
    #[serde(rename = "str")]
    Str { v: String },
    #[serde(rename = "bytes")]
    Bytes { v: String },
    #[serde(rename = "list")]
    List { v: Vec<TaggedValue> },
    #[serde(rename = "dict")]
    Dict { v: Vec<(TaggedValue, TaggedValue)> },
    #[serde(rename = "date")]
    Date { v: String },
    #[serde(rename = "datetime")]
    DateTime {
        naive: String,
        offset_seconds: Option<i64>,
    },
}

fn decode_hex(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

impl From<TaggedValue> for Value {
    fn from(tagged: TaggedValue) -> Self {
        match tagged {
            TaggedValue::None => Value::None,
            TaggedValue::Bool { v } => Value::Bool(v),
            TaggedValue::Int { v } => Value::Int(
                electricity_value::IntValue::parse_decimal(&v).expect("valid decimal integer"),
            ),
            TaggedValue::Float { bits } => {
                let bits = u64::from_str_radix(&bits, 16).expect("valid hex bit pattern");
                Value::Float(f64::from_bits(bits))
            }
            TaggedValue::Str { v } => Value::Str(v),
            TaggedValue::Bytes { v } => Value::Bytes(decode_hex(&v)),
            TaggedValue::List { v } => Value::List(v.into_iter().map(Value::from).collect()),
            TaggedValue::Dict { v } => {
                let mut dict = Dict::new();
                for (k, val) in v {
                    dict.insert(Value::from(k), Value::from(val));
                }
                Value::Dict(dict)
            }
            TaggedValue::Date { v } => {
                Value::Date(NaiveDate::parse_from_str(&v, "%Y-%m-%d").expect("valid ISO date"))
            }
            TaggedValue::DateTime {
                naive,
                offset_seconds,
            } => {
                let naive = NaiveDateTime::parse_from_str(&naive, "%Y-%m-%dT%H:%M:%S%.f")
                    .expect("valid ISO naive datetime");
                let offset = offset_seconds
                    .map(|secs| FixedOffset::east_opt(secs as i32).expect("valid UTC offset"));
                Value::DateTime(naive, offset)
            }
        }
    }
}

#[derive(Deserialize)]
struct SyntaxCase {
    template: String,
    syntax_error: Option<String>,
}

#[derive(Deserialize)]
struct RenderCase {
    template: String,
    ctx: TaggedValue,
    label: String,
    json_aware: bool,
    render_ok: Option<String>,
    render_err: Option<String>,
}

#[derive(Deserialize)]
struct Corpus {
    syntax_cases: Vec<SyntaxCase>,
    render_cases: Vec<RenderCase>,
}

/// A small JSON-ish serializer covering exactly the value shapes the
/// corpus's `json_aware` cases use (`None`/`Bool`/`Int`/`Str`/`List`/
/// `Dict`) -- deliberately not `electricity-json` (built in parallel,
/// DESIGN.md §3.3): `JsonAwareCtx` takes its serializer from the caller,
/// so this crate is tested against one of its own rather than depending
/// on that crate existing yet.
fn test_json_serialize(value: &Value) -> Result<String, String> {
    match value {
        Value::None => Ok("null".to_string()),
        Value::Bool(b) => Ok(if *b { "true" } else { "false" }.to_string()),
        Value::Int(i) => Ok(i.to_bigint().to_string()),
        Value::Str(s) => Ok(json_quote(s)),
        Value::List(items) => {
            let parts: Result<Vec<String>, String> =
                items.iter().map(test_json_serialize).collect();
            Ok(format!("[{}]", parts?.join(", ")))
        }
        Value::Dict(d) => {
            let parts: Result<Vec<String>, String> = d
                .iter()
                .map(|(k, v)| {
                    let key = match k {
                        Value::Str(s) => s.clone(),
                        other => other.py_str(),
                    };
                    Ok(format!("{}: {}", json_quote(&key), test_json_serialize(v)?))
                })
                .collect();
            Ok(format!("{{{}}}", parts?.join(", ")))
        }
        other => Err(format!(
            "test_json_serialize: unsupported value {:?}",
            other
        )),
    }
}

fn json_quote(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

#[test]
fn golden_corpus_syntax_errors() {
    let text = include_str!("golden/corpus.json");
    let corpus: Corpus = serde_json::from_str(text).expect("golden/corpus.json is valid JSON");
    assert!(!corpus.syntax_cases.is_empty());

    let mut failures = Vec::new();
    for (i, case) in corpus.syntax_cases.iter().enumerate() {
        let got = template_syntax_error(&case.template);
        if got != case.syntax_error {
            failures.push(format!(
                "syntax case {i} ({:?}): expected {:?}, got {:?}",
                case.template, case.syntax_error, got
            ));
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn golden_corpus_render() {
    let text = include_str!("golden/corpus.json");
    let corpus: Corpus = serde_json::from_str(text).expect("golden/corpus.json is valid JSON");
    assert!(!corpus.render_cases.is_empty());

    let mut failures = Vec::new();
    for (i, case) in corpus.render_cases.into_iter().enumerate() {
        let root = Value::from(case.ctx);
        let result = if case.json_aware {
            let ctx = JsonAwareCtx::new(&test_json_serialize);
            render_template(&case.template, &root, &ctx, &case.label)
        } else {
            render_template(&case.template, &root, &PlainCtx, &case.label)
        };
        match (result, case.render_ok, case.render_err) {
            (Ok(text), Some(expected), None) if text == expected => {}
            (Err(err), None, Some(expected)) if err.to_string() == expected => {}
            (got, expected_ok, expected_err) => failures.push(format!(
                "render case {i} ({:?}): expected ok={expected_ok:?} err={expected_err:?}, got {got:?}",
                case.template
            )),
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
