//! Replays the golden corpus generated by
//! `electricity/scripts/generate_tool_execute_corpus.py` -- real output
//! from Circuitry's own `core.tool.ToolRuntime.execute`, run against a
//! real `circuitry.core.store.Store` -- against this crate's
//! `exec::tool::execute_tool`.
//!
//! The corpus is checked in (`tests/golden/tool_execute_corpus.json`);
//! CI separately regenerates it with Python 3.11 and fails the build if
//! it differs (`.github/workflows/electricity-generated.yml`), so this
//! test only needs to trust the committed file.
//!
//! Every case's own `params`/`params_json`/`retries`/`expect` already
//! has `backoff_ms: 0` wherever retries are involved, so comparing the
//! final state needs no mock clock: a zero ceiling waits zero on both
//! sides of the port. `created_at`/`completed_at` are real wall-clock
//! timestamps on the Python side and are normalized away on both sides
//! before comparing, the same way `electricity/scripts/_run_corpus.py`'s
//! own normalizer treats them.

use electricity_bytecode::{
    EffectPath, Escape, ExpectCondition, LeafKind, NodeKind, OnError, Op, ParamNode, RetryPolicy,
    TemplateText, ToolOp,
};
use electricity_value::{Dict, Value};
use electricity_vm::{CancellationToken, Limiter, NullObserver, RunContext, Store, VmError};
use indexmap::IndexMap;
use serde::Deserialize;

#[derive(Deserialize, Debug, Clone)]
#[serde(tag = "t")]
enum TaggedValue {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "bool")]
    Bool { v: bool },
    #[serde(rename = "int")]
    Int { v: String },
    #[serde(rename = "float")]
    Float { bits: String },
    #[serde(rename = "str")]
    Str { v: String },
    #[serde(rename = "list")]
    List { v: Vec<TaggedValue> },
    #[serde(rename = "dict")]
    Dict { v: Vec<(TaggedValue, TaggedValue)> },
}

impl From<TaggedValue> for Value {
    fn from(tagged: TaggedValue) -> Self {
        match tagged {
            TaggedValue::None => Value::None,
            TaggedValue::Bool { v } => Value::Bool(v),
            TaggedValue::Int { v } => Value::Int(
                electricity_value::IntValue::parse_decimal(&v).expect("valid decimal integer"),
            ),
            TaggedValue::Float { bits } => {
                let bits = u64::from_str_radix(&bits, 16).expect("valid hex bit pattern");
                Value::Float(f64::from_bits(bits))
            }
            TaggedValue::Str { v } => Value::Str(v),
            TaggedValue::List { v } => Value::List(v.into_iter().map(Value::from).collect()),
            TaggedValue::Dict { v } => {
                let mut dict = Dict::new();
                for (k, val) in v {
                    dict.insert(Value::from(k), Value::from(val));
                }
                Value::Dict(dict)
            }
        }
    }
}

/// A `params`/`params_json` overlay shape built from a Python literal
/// dict (never a template or a `{from: ...}` reference, for every case
/// this corpus generates) turns into a [`ParamNode`] tree exactly the
/// way `electricity-compiler::compile::params::build_param_node` would
/// compile the same literal YAML: every string leaf -- regardless of
/// whether it contains `{{`/`{from:...}` syntax of its own -- becomes
/// [`ParamNode::Template`] (plain Mustache rendering of a tag-free
/// string is a no-op, matching a literal value exactly); dicts/lists
/// recurse; every other scalar is a [`ParamNode::Literal`].
fn value_to_param_node(value: &Value) -> ParamNode {
    match value {
        Value::Str(s) => ParamNode::Template(TemplateText::new(s.clone(), true, Escape::Html)),
        Value::Dict(dict) => {
            let mut map = IndexMap::new();
            for (k, v) in dict {
                map.insert(k.clone(), value_to_param_node(v));
            }
            ParamNode::Map(map)
        }
        Value::List(items) => ParamNode::List(items.iter().map(value_to_param_node).collect()),
        other => ParamNode::Literal(other.clone()),
    }
}

#[derive(Deserialize)]
struct RetriesCase {
    max_attempts: u32,
    backoff_ms: u32,
}

#[derive(Deserialize)]
struct ExpectCase {
    mode: String,
    expr: Option<String>,
}

#[derive(Deserialize)]
struct ToolExecuteCase {
    case: String,
    on_error: String,
    params: TaggedValue,
    params_json: Option<String>,
    retries: Option<RetriesCase>,
    expect: Option<ExpectCase>,
    runtime_config: TaggedValue,
    ctx: TaggedValue,
    raised: bool,
    error: Option<String>,
    node: TaggedValue,
}

#[derive(Deserialize)]
struct Corpus {
    tool_execute_cases: Vec<ToolExecuteCase>,
}

fn on_error_from_str(s: &str) -> OnError {
    match s {
        "fail" => OnError::Fail,
        "skip" => OnError::Skip,
        "continue" => OnError::Continue,
        other => panic!("unexpected on_error {other:?}"),
    }
}

/// Replaces every `created_at`/`completed_at` leaf under *value* with a
/// fixed placeholder -- real wall-clock timestamps on both sides of the
/// comparison, normalized away exactly the way `electricity/scripts/
/// _run_corpus.py`'s own normalizer treats them (matching only the
/// `YYYY-MM-DDTHH:MM:SS` prefix, never the exact instant).
fn normalize_timestamps(value: &mut Value) {
    match value {
        Value::Dict(dict) => {
            for (key, inner) in dict.iter_mut() {
                let is_timestamp_key = matches!(
                    key,
                    Value::Str(s) if s == "created_at" || s == "completed_at"
                );
                if is_timestamp_key && matches!(inner, Value::Str(_)) {
                    *inner = Value::Str("<TIMESTAMP>".to_string());
                } else {
                    normalize_timestamps(inner);
                }
            }
        }
        Value::List(items) => {
            for item in items {
                normalize_timestamps(item);
            }
        }
        _ => {}
    }
}

#[tokio::test]
async fn golden_corpus_execute_tool() {
    let text = include_str!("golden/tool_execute_corpus.json");
    let corpus: Corpus =
        serde_json::from_str(text).expect("golden/tool_execute_corpus.json is valid JSON");
    assert!(!corpus.tool_execute_cases.is_empty());

    let mut failures = Vec::new();
    for case in corpus.tool_execute_cases {
        let name = case.case.clone();
        let params_value = Value::from(case.params);
        let params_node = value_to_param_node(&params_value);
        let params_json = case
            .params_json
            .map(|text| TemplateText::new(text, true, Escape::Html));
        let retries = match case.retries {
            Some(r) => RetryPolicy {
                max_attempts: r.max_attempts,
                backoff_ms: r.backoff_ms,
            },
            None => RetryPolicy::default(),
        };
        let expect = case.expect.map(|e| {
            assert_eq!(
                e.mode, "cel",
                "case {name}: only CEL expect is used by this corpus"
            );
            ExpectCondition::Cel {
                expr: e.expr.expect("a cel expect always carries an expr"),
            }
        });
        let on_error = on_error_from_str(&case.on_error);

        let tool = ToolOp {
            provider: "json".to_string(),
            params: params_node,
            params_json,
            prompt: None,
            model: None,
            timeout_ms: None,
            retries,
            expect,
            description: None,
            group: None,
        };
        let op = Op {
            path: EffectPath::root().push_name(&name),
            name: Some(name.clone()),
            kind: NodeKind::Leaf(Box::new(LeafKind::Tool(tool.clone()))),
            on_error,
            labels: None,
            enabled: true,
        };

        let store = Store::new();
        let mut registry = electricity_tools::ToolRegistry::new();
        registry.register(Box::new(electricity_tools::json::JsonTool));
        let limiter = Limiter::new();
        let runtime_config = Value::from(case.runtime_config);
        let ctx = Value::from(case.ctx);
        let run_ctx = RunContext {
            registry: &registry,
            limiter: &limiter,
            model: "",
            adapter: "_noop",
            runtime_config: &runtime_config,
            dry_run: false,
        };
        let token = CancellationToken::new();

        let result = electricity_vm::exec::tool::execute_tool(
            &op,
            &tool,
            &store,
            &store.root,
            &ctx,
            &run_ctx,
            &NullObserver,
            &token,
        )
        .await;

        match (result, case.raised, case.error) {
            (Err(VmError::Tool(got_message)), true, Some(expected_message)) => {
                if got_message != expected_message {
                    failures.push(format!(
                        "case {name}: expected error {expected_message:?}, got {got_message:?}"
                    ));
                    continue;
                }
            }
            (Err(err), true, expected) => {
                failures.push(format!(
                    "case {name}: expected a VmError::Tool with {expected:?}, got {err:?}"
                ));
                continue;
            }
            (Ok(()), false, None) => {}
            (got, raised, error) => {
                failures.push(format!(
                    "case {name}: expected raised={raised} error={error:?}, got {got:?}"
                ));
                continue;
            }
        }

        let name_key = Value::Str(name.clone());
        let mut got_node = match store.root.borrow().get(&name_key) {
            Some(electricity_vm::store::Slot::Node(node)) => store.snapshot(node),
            Some(electricity_vm::store::Slot::Value(v)) => v.clone(),
            None => Value::None,
        };
        let mut expected_node = Value::from(case.node);
        normalize_timestamps(&mut got_node);
        normalize_timestamps(&mut expected_node);
        if got_node != expected_node {
            failures.push(format!(
                "case {name}: node mismatch\n  expected: {expected_node:?}\n  got:      {got_node:?}"
            ));
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n\n"));
}
