//! Replays the golden corpus generated by
//! `electricity/scripts/generate_json_read_corpus.py` against
//! `electricity_json::loads` and `electricity_json::load_json`.
//!
//! The corpus is checked in (`tests/golden/read_corpus.json`); CI
//! separately regenerates it with Python 3.11 (and Circuitry's own
//! `core.json_load.load_json` for the duplicate-key cases) and fails the
//! build if it differs (`.github/workflows/electricity-generated.yml`), so
//! this test only needs to trust the committed file.
//!
//! A `"syntax"` row's `message` is the full, exact text of CPython's own
//! `str(json.JSONDecodeError)` -- `electricity_json::ReadError::Syntax`'s
//! own Display is checked word for word against it, not just at the same
//! character position (issue #442).

use electricity_json::{ReadError, load_json, loads};
use electricity_value::{Dict, IntValue, Value};
use serde::Deserialize;

#[derive(Deserialize, Clone)]
#[serde(tag = "t")]
enum TaggedValue {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "bool")]
    Bool { v: bool },
    #[serde(rename = "int")]
    Int { v: String },
    #[serde(rename = "float")]
    Float { bits: String },
    #[serde(rename = "str")]
    Str { v: String },
    #[serde(rename = "list")]
    List { v: Vec<TaggedValue> },
    #[serde(rename = "dict")]
    Dict { v: Vec<(TaggedValue, TaggedValue)> },
}

impl From<TaggedValue> for Value {
    fn from(tagged: TaggedValue) -> Self {
        match tagged {
            TaggedValue::None => Value::None,
            TaggedValue::Bool { v } => Value::Bool(v),
            TaggedValue::Int { v } => {
                Value::Int(IntValue::parse_decimal(&v).expect("valid decimal integer literal"))
            }
            TaggedValue::Float { bits } => {
                let bits = u64::from_str_radix(&bits, 16).expect("valid hex bit pattern");
                Value::Float(f64::from_bits(bits))
            }
            TaggedValue::Str { v } => Value::Str(v),
            TaggedValue::List { v } => Value::List(v.into_iter().map(Value::from).collect()),
            TaggedValue::Dict { v } => {
                let mut dict = Dict::new();
                for (k, val) in v {
                    dict.insert(Value::from(k), Value::from(val));
                }
                Value::Dict(dict)
            }
        }
    }
}

#[derive(Deserialize, Clone)]
#[serde(tag = "kind")]
enum Expect {
    #[serde(rename = "ok")]
    Ok { value: TaggedValue },
    #[serde(rename = "duplicate_key")]
    DuplicateKey { message: String },
    #[serde(rename = "syntax")]
    Syntax { message: String },
}

/// Which of electricity-json's two reader entry points a row exercises
/// (`generate_json_read_corpus.py`'s `entry`): `loads` and `load_json` can
/// only disagree on a repeated object key, so most rows run against both.
#[derive(Deserialize)]
#[serde(rename_all = "snake_case")]
enum Entry {
    Loads,
    LoadJson,
    Both,
}

#[derive(Deserialize)]
struct Row {
    text: String,
    entry: Entry,
    expect: Expect,
}

/// `Value`'s `PartialEq` is Python dict-key equality (`py_eq`): `1`/`1.0`
/// are the same `Value` by that measure, but the reader must actually
/// produce an `Int`, not a `Float`, for a text like `"1"` -- so this
/// compares `py_repr()` (which does distinguish them), not `==`. Pushes
/// to `failures` rather than asserting directly so one mismatch doesn't
/// hide every other case's result in the same run.
fn check_same_value(got: &Value, expected: &Value, context: &str, failures: &mut Vec<String>) {
    let got_repr = got.py_repr();
    let expected_repr = expected.py_repr();
    if got_repr != expected_repr {
        failures.push(format!(
            "{context}: value mismatch: expected {expected_repr}, got {got_repr}"
        ));
    }
}

fn check(
    name: &str,
    result: Result<Value, ReadError>,
    expect: &Expect,
    context: &str,
    failures: &mut Vec<String>,
) {
    match (result, expect) {
        (Ok(got), Expect::Ok { value }) => {
            check_same_value(&got, &Value::from(value.clone()), context, failures);
        }
        (Ok(got), Expect::DuplicateKey { .. }) => failures.push(format!(
            "{context}: {name} expected a duplicate-key error, got {got:?}"
        )),
        (Ok(got), Expect::Syntax { .. }) => failures.push(format!(
            "{context}: {name} expected a syntax error, got {got:?}"
        )),
        (Err(ReadError::DuplicateKey { message }), Expect::DuplicateKey { message: expected }) => {
            if message != *expected {
                failures.push(format!(
                    "{context}: {name} duplicate-key message mismatch: expected {expected:?}, got {message:?}"
                ));
            }
        }
        (Err(got), Expect::DuplicateKey { message: expected }) => failures.push(format!(
            "{context}: {name} expected duplicate-key error {expected:?}, got {got}"
        )),
        (Err(err @ ReadError::Syntax { .. }), Expect::Syntax { message: expected }) => {
            let got_message = err.to_string();
            if got_message != *expected {
                failures.push(format!(
                    "{context}: {name} syntax error message mismatch: expected {expected:?}, got {got_message:?}"
                ));
            }
        }
        (Err(got), Expect::Syntax { message: expected }) => failures.push(format!(
            "{context}: {name} expected a syntax error {expected:?}, got {got}"
        )),
        (Err(got), Expect::Ok { .. }) => {
            failures.push(format!("{context}: {name} expected success, got {got}"))
        }
    }
}

#[test]
fn golden_read_corpus() {
    let text = include_str!("golden/read_corpus.json");
    let rows: Vec<Row> = serde_json::from_str(text).expect("golden/read_corpus.json is valid JSON");
    assert!(!rows.is_empty(), "golden read corpus must not be empty");

    let mut failures = Vec::new();
    for (i, row) in rows.into_iter().enumerate() {
        let context = format!("case {i} ({:?})", row.text);
        if matches!(row.entry, Entry::Loads | Entry::Both) {
            check(
                "loads",
                loads(&row.text),
                &row.expect,
                &context,
                &mut failures,
            );
        }
        if matches!(row.entry, Entry::LoadJson | Entry::Both) {
            check(
                "load_json",
                load_json(&row.text),
                &row.expect,
                &context,
                &mut failures,
            );
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
