//! Replays the golden corpus generated by
//! `electricity/scripts/generate_json_write_corpus.py` against
//! `electricity_json::dumps`/`dumps_default_str`.
//!
//! The corpus is checked in (`tests/golden/write_corpus.json`); CI
//! separately regenerates it with Python 3.11 and fails the build if it
//! differs (`.github/workflows/electricity-generated.yml`), so this test
//! only needs to trust the committed file.

use chrono::{FixedOffset, NaiveDate, NaiveDateTime};
use electricity_json::{Separators, WriteMode, dumps, dumps_default_str};
use electricity_value::{Dict, IntValue, Value};
use serde::Deserialize;

#[derive(Deserialize)]
#[serde(tag = "t")]
enum TaggedValue {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "bool")]
    Bool { v: bool },
    #[serde(rename = "int")]
    Int { v: String },
    #[serde(rename = "float")]
    Float { bits: String },
    #[serde(rename = "str")]
    Str { v: String },
    #[serde(rename = "bytes")]
    Bytes { v: String },
    #[serde(rename = "list")]
    List { v: Vec<TaggedValue> },
    #[serde(rename = "dict")]
    Dict { v: Vec<(TaggedValue, TaggedValue)> },
    #[serde(rename = "date")]
    Date { v: String },
    #[serde(rename = "datetime")]
    DateTime {
        naive: String,
        offset_seconds: Option<i64>,
    },
}

fn decode_hex(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

impl From<TaggedValue> for Value {
    fn from(tagged: TaggedValue) -> Self {
        match tagged {
            TaggedValue::None => Value::None,
            TaggedValue::Bool { v } => Value::Bool(v),
            TaggedValue::Int { v } => {
                Value::Int(IntValue::parse_decimal(&v).expect("valid decimal integer literal"))
            }
            TaggedValue::Float { bits } => {
                let bits = u64::from_str_radix(&bits, 16).expect("valid hex bit pattern");
                Value::Float(f64::from_bits(bits))
            }
            TaggedValue::Str { v } => Value::Str(v),
            TaggedValue::Bytes { v } => Value::Bytes(decode_hex(&v)),
            TaggedValue::List { v } => Value::List(v.into_iter().map(Value::from).collect()),
            TaggedValue::Dict { v } => {
                let mut dict = Dict::new();
                for (k, val) in v {
                    dict.insert(Value::from(k), Value::from(val));
                }
                Value::Dict(dict)
            }
            TaggedValue::Date { v } => {
                Value::Date(NaiveDate::parse_from_str(&v, "%Y-%m-%d").expect("valid ISO date"))
            }
            TaggedValue::DateTime {
                naive,
                offset_seconds,
            } => {
                let naive = NaiveDateTime::parse_from_str(&naive, "%Y-%m-%dT%H:%M:%S%.f")
                    .expect("valid ISO naive datetime");
                let offset = offset_seconds
                    .map(|secs| FixedOffset::east_opt(secs as i32).expect("valid UTC offset"));
                Value::DateTime(naive, offset)
            }
        }
    }
}

#[derive(Deserialize)]
struct WriteCase {
    mode: String,
    text: Option<String>,
    error: bool,
}

#[derive(Deserialize)]
struct Row {
    value: TaggedValue,
    cases: Vec<WriteCase>,
}

/// The `WriteMode`/`dumps` vs. `dumps_default_str` choice for each
/// `mode` name the generator emits (`generate_json_write_corpus.py`'s
/// `MODES`).
fn run(value: &Value, mode_name: &str) -> Result<String, String> {
    let result = match mode_name {
        "compact" => dumps(value, WriteMode::COMPACT),
        "pretty" => dumps(value, WriteMode::PRETTY),
        "ascii_false" => dumps(
            value,
            WriteMode {
                indent: None,
                sort_keys: false,
                ensure_ascii: false,
                separators: Separators::Default,
            },
        ),
        "default_str" => dumps_default_str(
            value,
            WriteMode {
                indent: None,
                sort_keys: false,
                ensure_ascii: false,
                separators: Separators::Default,
            },
        ),
        "compact_separators" => dumps(
            value,
            WriteMode {
                indent: None,
                sort_keys: false,
                ensure_ascii: true,
                separators: Separators::Compact,
            },
        ),
        "compact_separators_sorted" => dumps(
            value,
            WriteMode {
                indent: None,
                sort_keys: true,
                ensure_ascii: true,
                separators: Separators::Compact,
            },
        ),
        other => panic!("unknown mode {other:?} in write_corpus.json"),
    };
    result.map_err(|e| e.to_string())
}

#[test]
fn golden_write_corpus() {
    let text = include_str!("golden/write_corpus.json");
    let rows: Vec<Row> =
        serde_json::from_str(text).expect("golden/write_corpus.json is valid JSON");
    assert!(!rows.is_empty(), "golden write corpus must not be empty");

    let mut failures = Vec::new();
    for (i, row) in rows.into_iter().enumerate() {
        let value = Value::from(row.value);
        for case in row.cases {
            match (run(&value, &case.mode), case.error, case.text) {
                (Ok(got), false, Some(expected)) if got == expected => {}
                (Ok(got), false, Some(expected)) => failures.push(format!(
                    "case {i} mode {}: expected {expected:?}, got {got:?}",
                    case.mode
                )),
                (Ok(got), true, _) => failures.push(format!(
                    "case {i} mode {}: expected an error, got {got:?}",
                    case.mode
                )),
                (Err(_), false, _) => failures.push(format!(
                    "case {i} mode {}: expected success, got an error",
                    case.mode
                )),
                (Err(_), true, _) => {}
                (Ok(_), false, None) => unreachable!("non-error case always carries text"),
            }
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
