//! Replays the golden corpus generated by
//! `electricity/scripts/generate_tool_runtime_corpus.py` -- real output
//! from Circuitry's own `redact` (`cli/redaction.py`) for `redact_cases`
//! -- against this crate's `redact`. `cap_raw_cases` instead replay the
//! literal expression `core/tool.py::_capped_raw` uses for its own
//! `_preview` field (`encoded[:_RAW_META_MAX_BYTES].decode("utf-8",
//! errors="ignore")`), since `cap_raw` itself takes already-encoded
//! bytes with no single matching Python function (see the generator's
//! own module doc comment).
//!
//! The corpus is checked in (`tests/golden/corpus.json`); CI separately
//! regenerates it with Python 3.11 and fails the build if it differs
//! (`.github/workflows/electricity-generated.yml`), so this test only
//! needs to trust the committed file.

use electricity_redaction::{cap_raw, redact};
use electricity_value::{Dict, Value};
use serde::Deserialize;

#[derive(Deserialize, Debug)]
#[serde(tag = "t")]
enum TaggedValue {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "bool")]
    Bool { v: bool },
    #[serde(rename = "int")]
    Int { v: String },
    #[serde(rename = "float")]
    Float { bits: String },
    #[serde(rename = "str")]
    Str { v: String },
    #[serde(rename = "list")]
    List { v: Vec<TaggedValue> },
    #[serde(rename = "dict")]
    Dict { v: Vec<(TaggedValue, TaggedValue)> },
}

impl From<TaggedValue> for Value {
    fn from(tagged: TaggedValue) -> Self {
        match tagged {
            TaggedValue::None => Value::None,
            TaggedValue::Bool { v } => Value::Bool(v),
            TaggedValue::Int { v } => Value::Int(
                electricity_value::IntValue::parse_decimal(&v).expect("valid decimal integer"),
            ),
            TaggedValue::Float { bits } => {
                let bits = u64::from_str_radix(&bits, 16).expect("valid hex bit pattern");
                Value::Float(f64::from_bits(bits))
            }
            TaggedValue::Str { v } => Value::Str(v),
            TaggedValue::List { v } => Value::List(v.into_iter().map(Value::from).collect()),
            TaggedValue::Dict { v } => {
                let mut dict = Dict::new();
                for (k, val) in v {
                    dict.insert(Value::from(k), Value::from(val));
                }
                Value::Dict(dict)
            }
        }
    }
}

#[derive(Deserialize)]
struct RedactCase {
    input: TaggedValue,
    output: TaggedValue,
}

#[derive(Deserialize)]
struct CapRawCase {
    name: String,
    encoded_hex: String,
    original_bytes: u64,
    capped: bool,
    preview: String,
}

#[derive(Deserialize)]
struct Corpus {
    redact_cases: Vec<RedactCase>,
    cap_raw_cases: Vec<CapRawCase>,
}

fn decode_hex(hex: &str) -> Vec<u8> {
    (0..hex.len())
        .step_by(2)
        .map(|i| u8::from_str_radix(&hex[i..i + 2], 16).unwrap())
        .collect()
}

#[test]
fn golden_corpus_redact() {
    let text = include_str!("golden/corpus.json");
    let corpus: Corpus = serde_json::from_str(text).expect("golden/corpus.json is valid JSON");
    assert!(!corpus.redact_cases.is_empty());

    let mut failures = Vec::new();
    for (i, case) in corpus.redact_cases.into_iter().enumerate() {
        let input = Value::from(case.input);
        let expected = Value::from(case.output);
        let got = redact(input.clone());
        if got != expected {
            failures.push(format!(
                "redact case {i} ({input:?}): expected {expected:?}, got {got:?}"
            ));
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}

#[test]
fn golden_corpus_cap_raw() {
    let text = include_str!("golden/corpus.json");
    let corpus: Corpus = serde_json::from_str(text).expect("golden/corpus.json is valid JSON");
    assert!(!corpus.cap_raw_cases.is_empty());

    let mut failures = Vec::new();
    for case in corpus.cap_raw_cases {
        let encoded = decode_hex(&case.encoded_hex);
        assert_eq!(encoded.len() as u64, case.original_bytes, "{}", case.name);
        let marker = cap_raw(&encoded);
        if !case.capped {
            if marker.is_some() {
                failures.push(format!("{}: expected no cap, got one", case.name));
            }
            continue;
        }
        match marker {
            None => failures.push(format!("{}: expected a cap, got none", case.name)),
            Some(marker) => {
                if marker.original_bytes as u64 != case.original_bytes
                    || marker.preview != case.preview
                {
                    failures.push(format!(
                        "{}: expected original_bytes={} preview={:?}, got original_bytes={} preview={:?}",
                        case.name, case.original_bytes, case.preview, marker.original_bytes, marker.preview
                    ));
                }
            }
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
