//! Replays the golden corpus generated by
//! `electricity/scripts/generate_schema_corpus.py` -- synthetic documents
//! run through Circuitry's real `jsonschema.Draft7Validator` against its
//! own schema files -- against [`electricity_schema::orchestration_errors`]
//! and [`electricity_schema::profile_errors`].
//!
//! Only the accept/reject verdict and each violation's *location* (the set
//! of locations, since the two engines are not required to order errors
//! identically -- their disagreement would come only from third-party
//! message text neither side has to match, `DESIGN.md` §1, §12) are
//! compared; every message is checked non-empty but never compared to the
//! Python `jsonschema` text it came from -- except for the one piece of
//! message text Circuitry's own `_describe_schema_error` writes rather
//! than quotes from `jsonschema`: the `repr(err.instance)` -> `"value"`
//! substitution. For a case where that substitution fired on the Python
//! side (`value_substituted_messages`), this crate's own message is
//! checked to start the same way (issue #380 review, finding 4).
//!
//! The corpus is checked in (`tests/golden/corpus.json`); CI separately
//! regenerates it (via Circuitry's own validation) and fails the build if
//! it differs (`.github/workflows/electricity-generated.yml`), so this
//! test only needs to trust the committed file.

use electricity_schema::{orchestration_errors, profile_errors};
use serde::Deserialize;
use serde_json::Value;

#[derive(Deserialize)]
struct Case {
    name: String,
    schema: String,
    document: Value,
    valid: bool,
    locations: Vec<String>,
    #[serde(default)]
    value_substituted_messages: std::collections::BTreeMap<String, String>,
}

#[test]
fn golden_corpus_matches_circuitry() {
    let text = include_str!("golden/corpus.json");
    let cases: Vec<Case> = serde_json::from_str(text).expect("golden/corpus.json is valid JSON");
    assert!(!cases.is_empty(), "golden corpus must not be empty");

    let mut failures = Vec::new();
    for case in &cases {
        let errors = match case.schema.as_str() {
            "orchestration" => orchestration_errors(&case.document),
            "profile" => profile_errors(&case.document),
            other => panic!("case {:?}: unknown schema kind {other:?}", case.name),
        };

        let is_valid = errors.is_empty();
        if is_valid != case.valid {
            failures.push(format!(
                "case {:?}: expected valid={}, got valid={} (errors: {:?})",
                case.name, case.valid, is_valid, errors
            ));
            continue;
        }

        let mut got_locations: Vec<&str> = errors.iter().map(|e| e.location.as_str()).collect();
        got_locations.sort_unstable();
        let expected_locations: Vec<&str> = case.locations.iter().map(String::as_str).collect();
        if got_locations != expected_locations {
            failures.push(format!(
                "case {:?}: location mismatch: expected {:?}, got {:?}",
                case.name, expected_locations, got_locations
            ));
        }

        for error in &errors {
            if error.message.is_empty() {
                failures.push(format!(
                    "case {:?}: error at {:?} has an empty message",
                    case.name, error.location
                ));
            }
        }

        // Circuitry's own "repr(instance) -> value" substitution (issue #380
        // review, finding 4): where Python's _describe_schema_error dropped a
        // leading instance rendering in favour of "value" (`python_message`
        // always starts with "value " too, by construction -- see the
        // generator), electricity-schema's own message for the same location
        // must have made the same substitution. The wording *after* "value"
        // is third-party text neither side has to match (`jsonschema` 0.26
        // spells oneOf/anyOf failures differently from Python's own
        // `jsonschema`, and Python additionally appends a best-matching
        // sub-error suffix this crate doesn't produce) -- only the fact that
        // both sides dropped the instance dump in favour of "value" is
        // compared.
        for (location, python_message) in &case.value_substituted_messages {
            assert!(
                python_message.starts_with("value "),
                "generator bug: {python_message:?}"
            );
            let found = errors
                .iter()
                .any(|e| e.location == *location && e.message.starts_with("value "));
            if !found {
                failures.push(format!(
                    "case {:?}: no error at {:?} starts with the substituted \"value\" prefix \
                     the way Python's {:?} does (got: {:?})",
                    case.name, location, python_message, errors
                ));
            }
        }
    }
    assert!(failures.is_empty(), "{}", failures.join("\n"));
}
